- grok/grok/pipeline/scripts/rpm-creator/post_install_grok
- infrastructure/ami-tools/Rakefile
- infrastructure/ami-tools/ami-configurations/infrastructure-base-128gb.json
- infrastructure/ami-tools/packer-scripts/configure-grok-pipeline-ami
- infrastructure/ami-tools/packer-scripts/configure-grok-plumbing-ami
* Ensure pip version is current on the AMI
* Add warning about installing yum-s3 before s3-backed repo files. Doing this in the wrong order breaks yum, so give people an explicit warning so they don't get to find that out the hard way.
* Rakefile cleanups
* Add grok_repos dependency to validate stanzas so they don't choke when run in a fresh checkout
* Don't bother to re-download yum s3 plugin if it is present
* Don't download bootstrap-salt.sh if it is already present
* Don't download epel rpm if it is already present
* Replace hardcoded url for yum s3 plugin with a variable
* Run pip install -r requirements.txt in grok RPM postinstall script
> TAUR-1217 Fix grok pipeline package install

- infrastructure/README.md
- infrastructure/infrastructure/create-grok-rpm
- infrastructure/infrastructure/create-numenta-rpm
We use the commit count as the rpm release version, so when we switched to the numenta-apps repo, we started generating rpms that had lower release versions, and yum assumed they were outdated.
Bumping the rpm version to 1.7.1 to get yum to see that newer rpms are in fact newer.
> TAUR-1217 Fix rpm versions

- infrastructure/ami-tools/repos/nta-carbonite.repo
- infrastructure/ami-tools/repos/nta-thirdparty.repo
- infrastructure/saltcellar/grok-plumbing/files/repos/grok-development.repo
- infrastructure/saltcellar/grok-plumbing/files/repos/grok-release-candidates.repo
- infrastructure/saltcellar/grok-plumbing/files/repos/grok-releases.repo
- infrastructure/saltcellar/grok-plumbing/files/repos/marketplace-only.repo
- infrastructure/saltcellar/nta-yum/files/nta-carbonite.repo
- infrastructure/saltcellar/nta-yum/files/nta-thirdparty.repo
- infrastructure/saltcellar/role-grok/files/repos/grok-development.repo
- infrastructure/saltcellar/role-grok/files/repos/grok-release-candidates.repo
* Updated ami-tools/repos
* Updated salt formulas:
* Updated grok-plumbing
* Updated nta-yum
* Updated role-grok
public.numenta.com points to public.numenta.com.s3-website-us-west-2.amazonaws.com. This will make future updates a lot easier since we can redirect to new hosting without having to change the repo files on existing machines.
> TAUR-1228 Update nta-yum repo files to not require S3 credentials

- infrastructure/infrastructure/utilities/ssh.py
If warn_only isn't explicitly set to true, fabric.api.run fails so hard we can't check the command exit code, which breaks our retry logic.
This was causing our instance start script to sporadically fail during boot even though we had set it to retry the startup scripts.
> HOTIFIX Update settings to fabric.api.run so we can catch errors properly

- taurus/conf/application.conf
Set the default dynamo table suffix so it isn't blank and is obvious that it should be changed
> table_name_suffix should never be blank

- grok/grok/pipeline/src/bake_ami.py
Update to read from public.groksolutions.com/yum/x86_64 since that's where the rpms are now published.
> TAUR-990 We now publish rpms to public.groksolutions.com/yum

- htmengine/htmengine/runtime/anomaly_service.py
- nta.utils/nta/utils/message_bus_connector.py
- taurus/taurus/engine/runtime/dynamodb/definitions/metric_tweets_dynamodbdefinition.py
- taurus/taurus/engine/runtime/dynamodb/dynamodb_service.py
- taurus/tests/integration/runtime/dynamodb/dynamodb_service_test.py
- taurus/tests/unit/runtime/dynamodb/dynamodb_service_test.py
We'll need to rethink the solution. The initial solution was having trouble clearing the backlog and keeping up with incoming data even when we bumped up the cumulative write throughput to 900 and increased dynamodb-service concurrency to 16 on a powerful EC2 instance.
CC @oxtopus @jcasner @lscheinkman
> TAUR-1137 Revert tweet aggregation due to unacceptable processing latency

- infrastructure/infrastructure/create-grok-rpm
- infrastructure/infrastructure/create-grok-saltcellar-rpm
- infrastructure/infrastructure/create-infrastructure-python-rpm
- infrastructure/infrastructure/create-numenta-rpm
- infrastructure/infrastructure/infrastructure-python-postinstall
* Paths were changed when the infrastructure module was refactored to become installable with `setup.py`, update them in `create-numenta-rpm`
* Update $@ treatment in create-*-rpm scripts
* We now use `setup.py install` in the postinstall to properly add the infrastructure module to anaconda's site-python.
This now generates an rpm with contents
```
rpm -qlp numenta-infrastructure-python-1.7.1-223.noarch.rpm
/opt/numenta/products/infrastructure/DEPENDENCIES.md
/opt/numenta/products/infrastructure/LICENSE
/opt/numenta/products/infrastructure/README.md
/opt/numenta/products/infrastructure/infrastructure/__init__.py
/opt/numenta/products/infrastructure/infrastructure/create-grok-rpm
/opt/numenta/products/infrastructure/infrastructure/create-grok-saltcellar-rpm …
```
> Fix infrastructure-python-rpm generation

- htmengine/tests/unit/runtime/metric_streamer_util_test.py
@scottpurdy  @vitaly-krugl --Fixed the hard-coded 'chunk_size' values in metric_streamer_util_test
> TAUR 708 removed hard-coded values from metric_streamer_util_test @scottpurdy @vitaly-krugl

- infrastructure/saltcellar/numenta-python/init.sls
Some of the packages we're installing in python by default require gcc to build.
> Add compiler dependency onto anaconda

- infrastructure/ami-tools/ami-configurations/grok-pipeline.json
- infrastructure/ami-tools/packer-scripts/configure-grok-pipeline-ami
The epel repository is available as an RPM. We've been installing it by just copying a file into `/etc/yum.repos.d`, but that is a bad idea since that file isn't getting updated and the epel-release RPM is.
The grok-pipeline now uses the `install-epel-repo-6.5` packer script to remove the old stale repo file, update ca-certificates (if we don't get current on ca-certificates, the epel repo will cause yum to fail SSL checks), then install the epel repo via the rpm.
This change was already applied to the grok-plumbing packer configuration when I initially implemented it for our infrastructure AMIs in [#72](https://github.com/numenta/numenta-apps/pull/72) somehow we missed adding it to the grok-pipeline packer configuration then.
> TAUR-1217 Fix epel repo installation

- infrastructure/saltcellar/mysql/client.sls
- infrastructure/saltcellar/mysql/server.sls
* Make the state names generic so we can change where we get the RPMs from more easily. This should make the CentOS 7 upgrade less painful.
* Fix parse error in mysql.server.sls
> Fix issues with mysql formula

- infrastructure/saltcellar/numenta-python/init.sls
- infrastructure/saltcellar/rabbitmq/init.sls
* Stop attempting to install rabbitmq_management if it is already installed.
* Ensure that rabbitmq-server is restarted after installing the management plugin
> TAUR-1272 Update rabbitmq dependency information

- infrastructure/saltcellar/mysql/server.sls
We weren't guaranteeing a restart of the mysqld server when we update `/etc/my.cnf`
It is bad practice to name the state after the config file path instead of using a symbolic name, so fixed that too.
> Restart mysqld service when we turn on the slow query log

- infrastructure/saltcellar/dotfiles/files/bash_profile_skeleton.sh
- infrastructure/saltcellar/dotfiles/files/zshrc_skeleton.zsh
Make login less spammy. We now only show ssh keys when they're actually present.
This also squelches console spam when the grok init script drops privileges to ec2-user during service startup.
@shantanoo @jcasner please CR.
> Stop zsh and bash from complaining about no ssh-agent

- grok/grok/app/aws/instance_utils.py
Don't retrieve EC2 metadata if running on Mac OS. This removes the significant delay that was occurring when loading the Grok GUI on Mac OS X as well as anything else that used grok/app/aws/instance_utils.py
> TAUR-834 Don't retrieve EC2 metadata if running on Mac OS.

- grok/grok/test_utils/app/test_case_base.py
@jcasner This causes the test to pass in the slower instance type. re: https://jira.numenta.com/browse/TAUR-1284
> TAUR-1284 Increase timeout in checkModelDeleted() from 25 to 60

- grok/grok/app/adapters/datasource/autostack/__init__.py
- grok/grok/app/webservices/models_api.py
If import-model-spec is passed to _AutostackDatasourceAdapter.getInstanceNameForModelSpec, attempt to map the autostack name/region to autostack id. If autstack doesn't exist, return None as permitted by DatasourceAdapterIface.getInstanceNameForModelSpec
> TAUR-834 Extend _AutostackDatasourceAdapter.getInstanceNameForModelSpec to support import-model-spec

- htmengine/htmengine/algorithms/modelSelection/anomaly_params_random_encoder/5AnomalyEnergyWithTimeCentroids_0_params.json
- htmengine/htmengine/algorithms/modelSelection/anomaly_params_random_encoder/5AnomalyEnergyWithTimeCentroids_1_params.json
- htmengine/htmengine/algorithms/modelSelection/anomaly_params_random_encoder/5AnomalyEnergyWithTimeCentroids_2_params.json
- htmengine/htmengine/algorithms/modelSelection/anomaly_params_random_encoder/5AnomalyEnergyWithTimeCentroids_3_params.json
- htmengine/htmengine/algorithms/modelSelection/anomaly_params_random_encoder/5AnomalyEnergyWithTimeCentroids_4_params.json
- htmengine/htmengine/algorithms/modelSelection/scalarMetricWithTimeOfDayAnomalyParams/5AnomalyEnergyWithTimeCentroids_0_params.json
- htmengine/htmengine/algorithms/modelSelection/scalarMetricWithTimeOfDayAnomalyParams/5AnomalyEnergyWithTimeCentroids_1_params.json
- htmengine/htmengine/algorithms/modelSelection/scalarMetricWithTimeOfDayAnomalyParams/5AnomalyEnergyWithTimeCentroids_2_params.json
- htmengine/htmengine/algorithms/modelSelection/scalarMetricWithTimeOfDayAnomalyParams/5AnomalyEnergyWithTimeCentroids_3_params.json
This issue was introduced in https://github.com/GrokSolutions/products/pull/768. The fix renames "columnDimensions" -> "potentialPct" in htmengine/algorithms/modelSelection parameter files.
NOTE that this change does not fully address TAUR-873. There are also issues in nupic that separately contribute to the failure.
> TAUR-873 Fixed incorrect SP configuration property names

- nta.utils/tests/integration/synchronous_amqp_client_test.py
Makes sure that tests won't fail if responses from RabbitMQ don't have the proper keys in their responses. Since these tests are wrapped with the `_RETRY_ON_ASSERTION_ERROR` decorator, they will now retry rather than failing. 
@oxtopus Please review
> Updated synchronous_amqp_client_test to assert RabbitMQ has keys in responses

- infrastructure/ami-tools/packer-scripts/cleanup-grok-pipeline-ami
- infrastructure/ami-tools/packer-scripts/cleanup-image
- infrastructure/ami-tools/packer-scripts/cleanup-infrastructure-ami
- infrastructure/ami-tools/packer-scripts/configure-infrastructure-ami
- infrastructure/ami-tools/packer-scripts/install-devtools
- infrastructure/ami-tools/packer-scripts/install-salt
* Add openssl-dev to AMIs
* Configure salt to use our salt master without us monkeying with '/etc/resolv.conf`
* Preset minion id so salt's bootstrap.sh doesn't attempt to use the default one that isn't preset to be approved on the master
* Turn on debug mode in `bootstrap.sh` so we can see details when it fails
* Add mysql-python to the AMI to try and fix TAUR-851's salt double-run problem
* We only want to purge authorized_keys on grok AMIs so we can pass marketplace acceptance, not every AMI.
> TAUR-1271 TAUR-851 Update ami bake

- infrastructure/saltcellar/rabbitmq/init.sls
> TAUR-1272 turn off gpg check because it's failing in salt currently; the gpg key provided by packagecloud is invalid

- infrastructure/ami-tools/packer-scripts/cleanup-grok-pipeline-ami
- infrastructure/ami-tools/packer-scripts/cleanup-infrastructure-ami
- infrastructure/ami-tools/packer-scripts/cleanup-webserver-ami
- infrastructure/ami-tools/packer-scripts/configure-grok-pipeline-ami
- infrastructure/ami-tools/packer-scripts/configure-grok-plumbing-ami
- infrastructure/ami-tools/packer-scripts/configure-webserver-ami
If we need to log the output of the individual packer scripts, we should be doing it by piping the stdout/in from our rake task to a file. Writing it to logs on the instance being used for ami bakes isn't effective because it leaves junk on the AMI, and if the AMI bake fails, packer terminates the instance and we won't be able to look at the log files anyway.
@jcasner @shantanoo @oxtopus please CR
> Strip out complain/logline from AMI build packer-scripts

- infrastructure/saltcellar/numenta-python/init.sls
Instead, let the applications that need them specify the version they need in their requirements.txt.
If we use a third party app that needs them and _doesn't_ have them in their requirements.txt we can make a state that installs the version they need on just the instances using that role.
@jcasner @shantanoo please CR.
> TAUR-1324 Remove psutil, supervisord from standard infrastructure load

- infrastructure/saltcellar/numenta-python/init.sls
We want whatever is the latest, not 18.0.1 specifically.
@oxtopus, please CR. Also, do you want to make pip install the latest pip too?
> TAUR-1324 Don't version-lock setuptools

- infrastructure/saltcellar/sudoers-setup/files/sudoers
Given that we already require SSH keys to login and don't permit password authentication, we're already granting passwordless sudo.
Having requiretty enabled doesn't give us any extra security anyway per: https://unix.stackexchange.com/questions/65774/is-it-okay-to-disable-requiretty and !visiblepw is irrelevant since we're granting passwordless sudo and relying on SSH key authentication.
@jcasner, @oxtopus, @shantanoo please CR.
> TAUR-1351 Disable requiretty and !visiblepw in /etc/sudoers

- infrastructure/infrastructure/utilities/cli.py
Follow up to: https://github.com/numenta/numenta-apps/pull/180#issuecomment-127796707
There are still warnings for the arguments to runWithOutput.
@vitaly-krugl
> Updated cli.py based on pylint

- infrastructure/saltcellar/rabbitmq/init.sls
We'll need to update the carbonite repo to prevent having to make this kind of last minute version update [TAUR-1382](https://jira.numenta.com/browse/TAUR-1382).
@oxtopus @jcasner please CR
> TAUR-1373 Upstream updated to 3.5.4, 3.5.3 is no longer available

- taurus.monitoring/setup.py
- taurus.monitoring/taurus/monitoring/supervisord_monitor/__init__.py
- taurus.monitoring/taurus/monitoring/supervisord_monitor/supervisord_monitor.py
- taurus.monitoring/taurus/monitoring/supervisord_monitor/taurus_collector_supervisord_monitor.py
- taurus.monitoring/taurus/monitoring/supervisord_monitor/taurus_server_supervisord_monitor.py
Adds an implementation for checking supervisor status, including whether or not there are any services in a FATAL state and sends an email with the details.  Intended to be run as a periodic cron job.
Usage:
```
taurus-server-supervisor-monitor --serverUrl=http://HOST:PORT --monitorConfPath=REDACTED
taurus-collector-supervisor-monitor --serverUrl=http://HOST:PORT --monitorConfPath=REDACTED
```
cc @unixorn
> TAUR-1371 Add supervisord checker

- pylintrc
Removed unnecessary nupic.support.lint.executable from load-plugins setting in pylintrc that was causing pylint to fail.
Formalize indent-after-paren=2 in pylintrc per nupic python coding guidelines of 2 spaces per indent.
> Deleting breaking configuration and formalized indent-after-paren in pylintrc

- unicorn/backend/unicorn_backend/model_runner.py
the temporary work-around for ILLEGAL INSTRUCTION on my dev laptop now is to build nupic from source.
> ENG-25 Enable the production code path that instantiates the real NuPIC model instead of dummy model

- infrastructure/saltcellar/agamotto/init.sls
Ensure we don't end up with stray root-owned files in anaconda's site-packages
> nose and agamotto installs should set watch_in for enforce-anaconda-permissions

- unicorn/frontend/browser/app.js
- unicorn/frontend/browser/components/foo.jsx
- unicorn/frontend/browser/lib/DatabaseClient.js
- unicorn/frontend/browser/lib/DatabaseClientHTTP.js
- unicorn/frontend/browser/lib/FileClient.js
- unicorn/frontend/browser/lib/FileClientHTTP.js
- unicorn/frontend/browser/lib/ModelClient.js
- unicorn/frontend/browser/lib/ModelClientHTTP.js
- unicorn/frontend/lib/DatabaseServer.js
- unicorn/frontend/lib/ModelServer.js
- unicorn/gulpfile.babel.js
- unicorn/package.json
UNI-148 #comment Init working Client/Server code for Files, Models, DBs.
Client IPC adapters are virtual using Electron's `remote`, but could be easily
specified and extended in the future.  These are sadly currently in ES5, as `remote` can't seem
to understand ES6 Classes and -some- syntax, couldn't figure out why.
Demo Client HTTP adapters also created to illustrate a REST API backend.
FileClient/Server still working end-to-end.
Also Bump a few pkg ver #'s.
https://jira.numenta.com/browse/UNI-148
https://jira.numenta.com/browse/UNI-150
https://jira.numenta.com/browse/UNI-153
https://jira.numenta.com/browse/UNI-154
FYI @lscheinkman @marionleborgne @jcasner
> UNI-148 #comment Init working Client/Server code for Files, Models, DBs.

- taurus.metric_collectors/taurus/metric_collectors/xignite/xignite_security_news_agent.py
- taurus.metric_collectors/taurus/metric_collectors/xignite/xignite_stock_agent.py
- taurus.metric_collectors/tests/integration/metric_utils_test.py
ENG-32 Added timeout in HTTP requests in xignite stock and news agents.
ENG-32 Fixed clean-up logic in the testCreateAllModels test method in integration/metric_utils_test.py.
> ENG-32 Added timeout in HTTP requests in xignite stock and news agents.

- grok/tests/py/integration/app/adapters/datasource/cloudwatch/cw_datasource_metric_specific_test.py
FYI @vitaly-krugl per our conversation earlier.
> TAUR-386 disable long running tests until they're moved to be nightly tests

- taurus.metric_collectors/conf/supervisord.conf
- taurus/conf/supervisord.conf
@oxtopus this is allow remote monitoring of the taurus server and collector. The security groups in EC2 will limit access to 9001 on the taurus instances to the monitoring server.
cc: @vitaly-krugl 
> TAUR-1383 Make supervisord listen on all interfaces

- taurus.metric_collectors/conf/supervisord.conf
- taurus/conf/supervisord.conf
Address @oxtopus's feedback on [numenta-apps/pull/299](https://github.com/numenta/numenta-apps/pull/299)
We only use IPv4, and given that the way we're using EC2 triggers undesired behavior in supervisord let's go with a configuration that works reliably.
@oxtopus please CR
cc: @jcasner
> Use 0.0.0.0 instead of * in supervisord.conf port setting

- infrastructure/saltcellar/nta-nucleus/packages.sls
We install an up-to-date version of git in our nta-git package; CentOS 6 has a very stale version, so remove it.
> Remove stale CentOS 6 git package

- unicorn/tests/py/integration/model_runner_test.py
ENG-26 Switch (float, int) variant in testFeedInputGetOutput back to just checking for float since we're now using AnomalyLikelihood class that always returns a float.
> ENG-26 Switch (float, int) variant in testFeedInputGetOutput back to just checking for float

- unicorn/frontend/browser/app.js
@brev  Please review.
See http://fluxible.io/api/plugins.html
This plugin will expose `ModelClient`, `FileClient`, `DBClient` to `FluxibleContexts`
We can limit access to `actionContext` only if you prefer.
Let me know what you think?
> UNI-164: Add Unicorn Fluxible plugin

- infrastructure/saltcellar/devtools/init.sls
Make sure the CentOS devtools don't get pulled in on non-CentOS machines
> UNI-169 We now need to support OS X build slaves

- unicorn/package.json
Last week `node` and `iojs` merged into `node 4` simplifying things for `node` developers. 
A few days later `electron` followed suit and replaced `iojs` with `node 4.1.0` simplifying things for `electron` developers.
Once this PR is merged you will need to upgrade node on your development machine and refresh `unicorn` dependencies with the following commands:
```shell
brew update
brew upgrade node
npm run clean
npm install
```
@unixorn Once this PR is merged we will need to install `node 4.1.0` on the build machine
CC: @brev @marionleborgne @jcasner
> Update to electron 0.33.0 which is based on node 4.1.0

- htmengine/requirements.txt
- htmengine/tests/integration/result_quality_test.py
This depends on an as of now, not yet completed 0.3.2 release of nupic in which the `nupic.bindings` dependency have been updated.
cc @scottpurdy
> Fixup result_quality_test to be consistent with cross-platform results

- infrastructure/saltcellar/motd/files/update-motd.centos
- infrastructure/saltcellar/motd/init.sls
Make motd formula work on both CentOS and OSX
* Set group ownership from root (CentOS only) to wheel, which exists on both platforms
* Get acta-diurna directly from GH instead of via an RPM
@lscheinkman, @shantanoo, @jcasner please CR
> UNI-169 Multi os support

- taurus.metric_collectors/taurus/metric_collectors/collectorsdb/__init__.py
- taurus.metric_collectors/taurus/metric_collectors/twitterdirect/twitter_direct_agent.py
- taurus.metric_collectors/taurus/metric_collectors/xignite/xignite_security_news_agent.py
- taurus.metric_collectors/tests/integration/collectorsdb_test.py
- taurus.metric_collectors/tests/unit/collectorsdb_test.py
ENG-67 We've experienced race condition hangs when the non-empty _EngineSingleton was cloned via multiprocessing forking. `cls._engine.dispose()` didn't alleviate this problem. The fix is
to fork the worker processes before anything in the main process invokes collectorsdb.engineFactory().
ENG-67 Fix unit tests to expect AssertionError when pid doesn't match the current pid.
ENG-67 In testEngineFactorySingletonPattern: expect AssertionError from collectorsdb.engineFactory() after populating the singleton in current process and requesting the engine again from a forked process
> ENG-67 Fix race condition that stalls tweet collector

- infrastructure/saltcellar/motd/init.sls
Salt won't replace a symlink with a file, so add states to clear the stale versions out of the way first.
@shantanoo, @lscheinkman, please CR.
> UNI-169 Make salt blow away the conflicting symlinks explicitly

- infrastructure/saltcellar/numenta-python/init.sls
Change ownership of /opt/numenta/anaconda according to the setting in /etc/numenta/anaconda-owner. If file doesn't exist, use ec2-user:ec2-user.
Cc: @jcasner, @unixorn
> TAUR-1301 Change the ownership for /opt/numenta/anaconda

- nta.utils/nta/utils/error_reporting.py
- taurus.metric_collectors/tests/deployment/resource_accessibility_test.py
ENG-62 Implement an additional taurus metric collectors deployment resource accessibility test that validates the account's authorization to send emails (used for error-reporting) via the collector's SES configuration.
NOTE: This bit us during the initial deployment of the integrated stock symbol and twitter handle services.
> ENG-62 Implement an additional taurus metric collectors deployment resource accessibility test

- infrastructure/saltcellar/numenta-python/files/correct-anaconda-ownership
- infrastructure/saltcellar/numenta-python/init.sls
The old cmd.run didn't work, probably because of the `&&` and `||` entries in the name clause
Using a tool script also allows us to call this in more from our other
infrastructure salt formulas
cc: @shantanoo @jcasner
> Hotfix anaconda permission change issue

- taurus.metric_collectors/taurus/metric_collectors/metric_utils.py
@oxtopus
Confusing docstring in `deleteMetric()` #231 
changed docstring at line 322 to ":param metricName: name of the metric to be deleted",
> fixes #231: 

- taurus/pipeline/scripts/update-remote-taurus-servers.sh
This adds an extra step to check that there are no "STOPPING" or "RUNNING" supervisor services before finally shutting down.
> Wait for services to stop

- htm.it/README.rst
- htm.it/htm/it/pipeline/README.md
- infrastructure/ami-tools/packer-scripts/configure-htm-it-pipeline-centos6.5-ami
- infrastructure/ami-tools/packer-scripts/configure-htm-it-pipeline-centos7-ami
- install-htm-it-from-bare-centos7.sh
- install-htm-it.sh
- install-infrastructure.sh
- install-taurus-metric-collectors.sh
- install-taurus-monitoring
- install-taurus.sh
- taurus/README.md
- taurus/pipeline/scripts/initialize-remote-taurus-servers.sh
- taurus/pipeline/scripts/refresh-remote-taurus-servers.sh
- taurus/pipeline/scripts/update-remote-taurus-servers.sh
It's just simpler to have to specify a single prefix rather than two paths.  In practice, the two paths always share a common prefix anyway.
Requires `install-prefix` companion branch in internal infrastructure repository.
> Install using revised python prefix as opposed to split package install location and script dir

- infrastructure/requirements.txt
- infrastructure/saltcellar/rabbitmq/init.sls
- infrastructure/setup.py
Changed our requirements to be `>=`, not `==`. We had run into an issue where taurus specified an exact version of 3.11 for PyYAML and infrastructure was specifying exactly 3.10.
The infrastructure module needs to be less picky so that it won't conflict with our other modules.
Deal with upstream update, 3.5.4 is no longer available.
TODO: [DEVOPS-31](https://jira.numenta.com/browse/DEVOPS-31) - Update the carbonite repo with all the rpms we're currently using so we don't have to upgrade packages just because upstream did.
> TAUR-1538 Update rabbitmq version & infrastructure module changes

- infrastructure/infrastructure/utilities/numenta_rpm.py
- infrastructure/setup.py
This was causing setup.py bdist upload to fail for the infrastructure module, which we need to do to resolve [TAUR-1538](https://jira.numenta.com/browse/TAUR-1538)
```
byte-compiling build/bdist.linux-x86_64/dumb/opt/numenta/anaconda/lib/python2.7/site-packages/infrastructure/utilities/numenta_rpm.py to numenta_rpm.pyc
File "/opt/numenta/anaconda/lib/python2.7/site-packages/infrastructure/utilities/numenta_rpm.py", line 372
SyntaxError: can't assign to operator
```
> Fix a breakage caused by grok->htm-it rename.

- htm.it/htm/it/app/aws/asg_utils.py
- htm.it/htm/it/app/aws/cloudwatch_utils.py
- htm.it/htm/it/app/aws/ec2_utils.py
- htm.it/htm/it/app/aws/elb_utils.py
- htm.it/htm/it/app/aws/opsworks_utils.py
- htm.it/htm/it/app/aws/rds_utils.py
- htm.it/htm/it/app/aws/s3_utils.py
- htm.it/htm/it/test_utils/app/test_case_base.py
- htm.it/tests/py/integration/app/runtime/metric_collector_int_test.py
Fixes https://jira.numenta.com/browse/ENG-51
This is the next PR for this issue after #412 had to be reverted by #415 
This passes all tests for htm.it and all but one test for taurus, which also fails on master, as described in: https://jira.numenta.com/browse/TAUR-1578
@scottpurdy This is ready for review.
> ENG-51 Replace use of nupic.support.decorators.retry with retry decorator from nta.utils

- htmengine/htmengine/model_swapper/slot_agent.py
- htmengine/tests/unit/model_swapper/slot_agent_test.py
@scottpurdy, please review. This addresses your feedback from #446
> ENG-85 Address Scott's feedback regarding log-level logic in SlotAgent._runEventLoop.stopModel closure. Add unit test for failed model runner.

- htmengine/tests/integration/model_swapper/slot_agent_test.py
Increased timeout in test and added a log line.
CC @scottpurdy
> ENG-91 Fixed transient failure of testStartMultipleModelRunnersAndStopThem integration test

- unicorn/backend/setup.py
Move evaluation of `testsLocation = resource_filename("unicorn_backend.tests", "")` to a part of the code in which "unicorn_backend" is resolvable.
> Move tests location calculation

- nta.utils/nta/utils/config.py
- nta.utils/tests/unit/config_test.py
- taurus.metric_collectors/tests/deployment/resource_accessibility_test.py
- taurus/conf/application.conf
- taurus/pipeline/scripts/initialize-remote-taurus-servers.sh
- taurus/pipeline/scripts/refresh-remote-taurus-servers.sh
- taurus/pipeline/scripts/update-remote-taurus-servers.sh
- taurus/setup.py
- taurus/taurus/engine/set_api_key.py
- taurus/taurus/engine/set_rabbitmq_login.py
- taurus/tests/unit/set_api_key_test.py
ENG-95 Impelement taurus-set-api-key console script for overriding Taurus Engine's REST API Key.
ENG-95 Updated Taurus pipeline scripts to override Taurus Engine's REST API Key using the new tool.
> ENG-95 Override Taurus Engine's REST API Key in Taurus pipelines

- htmengine/htmengine/adapters/datasource/custom/__init__.py
- htmengine/htmengine/runtime/scalar_metric_utils.py
- htmengine/tests/integration/custom_metrics_test.py
This is some prep work for working on ENG-98
ENG-98 Fix non-unique metric names in several tests.
ENG-98 Log metric name in scalar_metric_utils._startModelHelper
> ENG-98 prep - fixed some irregularities in custom_metrics_test and enhanced logging info when creating a model

- taurus.metric_collectors/taurus/metric_collectors/delete_companies.py
- taurus.metric_collectors/tests/unit/delete_companies_test.py
- taurus/taurus/engine/runtime/dynamodb/dynamodb_service.py
After deploying https://jira.numenta.com/browse/TAUR-964 to production via http://jenkins-master.numenta.com/job/graceful-update-production-taurus-servers/19/, I tried to validate the expected company changes by correlated references to them in dynamodb_service and metric_maintenance_agent logs.
It turned out to be difficult, since metric_maintenance_agent logged just the metric name of the deleted model, while dynamoddb_service logged just the unique id.
This PR addresses the shortcoming.
> Improve logging of models deleted by metric_maintenance_agent

- unicorn/js/main/ModelService.js
@marionleborgne @brev 
This is a workaround `OSError: [Errno 1] Operation not permitted: ....` issues on `El Capitan` when running `cx_freeze`
> Rollback `cx_freeze` until `El Capitan` issues are solved

- infrastructure/infrastructure/utilities/ec2.py
DEVOPS-67 Suppress InvalidInstanceID.NotFound in launchInstance; may happen due to eventual consistency.
DEVOPS-67 More robust termination of instance when error interrupts waiting for instance to enter running state.
> DEVOPS-67 Suppress InvalidInstanceID.NotFound in launchInstance

- taurus/pipeline/scripts/refresh-remote-taurus-servers.sh
CC @oxtopus, @scottpurdy 
ENG-98 In refresh-remote-taurus-servers.sh, reset rabbitmq node to virgin state and remove all checkpoints instead of deleting models via API, to fix CI pipeline timeout errors.
> ENG-98 Fix Taurus refresh pipeline timeouts

- taurus/docker/taurus/conf/application.conf
fixes ENG-104
@vitaly-krugl please review
> Remove unused logging AWS credentials from Taurus.

- nta.utils/nta/utils/tools/supervisord_state.py
- taurus/pipeline/scripts/refresh-remote-taurus-servers.sh
- taurus/pipeline/scripts/update-remote-taurus-servers.sh
CC @scottpurdy, @oxtopus
ENG-84 Cleaned up server stop/start logic in update-remote-taurus-servers.sh.
ENG-84 Added necessary nta-wait-for-supervisord-stopped to eliminate stop/start race condition.
ENG-84 In nta.utils.tools.supervisord_state.waitForStoppedStateMain, wait only for socket.error to conclude that supervisord is not available in order to eliminate race condition with re-starting logic.
ENG-84 Removed unnecessary supervisord shutdown of metric collector before running resource accessibility test, since the server was already shut down at the top of the script.
> ENG-84 Fix race condition in taurus update pipeline's server stop/start logic

- htm.it/tests/py/unit/app/aws/asg_utils_test.py
- htm.it/tests/py/unit/app/aws/ec2_utils_test.py
- htm.it/tests/py/unit/app/aws/elb_utils_test.py
- htm.it/tests/py/unit/app/aws/rds_utils_test.py
- htm.it/tests/py/unit/app/runtime/aggregation_test.py
- htm.it/tests/py/unit/app/webservices/logging_api_test.py
> Fix misspelled assert function names in htm.it unit tests

- imbu/engine/fluent_api.py
When creating a model, the runner would first initialize a model instance and then attempt loading a saved model. When loading a saved model, this initialization step is unnecessary. To avoid this I've added a `loadModel()` method and reordered the logic.
@oxtopus please review. I ran into issues adding `cPickle` to the requirements.txt.
> Initialize NLP model after attempt at loading

- imbu/engine/fluent_api.py
The `preprocess` param is not currently supported for queries.
@lscheinkman the models should run now.
> Remove preprocess param from Imbu queries

- imbu/gui/browser/components/search-results.jsx
IMBU-83 #comment Fix table header height in Firefox, now matches across browsers.
https://jira.numenta.com/browse/IMBU-83
> IMBU-83 #comment Fix table header height in Firefox, now matches across browsers.

- unicorn/js/config/momentjs_to_datetime_strptime.json
- unicorn/py/requirements.txt
- unicorn/py/unicorn_backend/agg_opt_schema.json
- unicorn/py/unicorn_backend/input_opt_schema.json
- unicorn/py/unicorn_backend/model_opt_schema.json
- unicorn/py/unicorn_backend/model_runner_2.py
- unicorn/py/unicorn_backend/tests/integration/model_runner_2_test.py
- unicorn/py/unicorn_backend/tests/unit/model_runner_2_test.py
CC @scottpurdy @marionleborgne @ywcui1990 
The new Model Runner module is initially named `model_runner_2.py`, while we still have the original around. We can get rid of the old and rename the new module after FrontEnd integrates with the new Model Runner.
> UNI-300 Implemented model_runner per phase 2 ModelRunner interface specification

- unicorn/js/browser/actions/FileUpload.js
- unicorn/js/browser/actions/ListMetrics.js
- unicorn/js/main/FileService.js
- unicorn/js/main/Utils.js
- unicorn/package.json
UNI-305 #comment Convert all CSV input to unix newlines.  `CR` and `CRLF` both converted to `LF` default.
This is a first bit of progress against https://jira.numenta.com/browse/UNI-305, more PR's soon as I continue investigation.
This allows LG data to be loaded, displayed quickly, and then you can start the crawling model.
Please review @marionleborgne or @lscheinkman thanks.
> UNI-305 Convert all CSV input to unix newlines

- unicorn/README.md
- unicorn/package.json
- Back to non-beta babel-eslint version, fix lint
- Update README to get rid of text about modules we're not using
@lscheinkman @marionleborgne
> Few small post-upgrade fixes:

- unicorn/js/config/momentjs_to_datetime_strptime.json
- unicorn/py/unicorn_backend/date_time_utils.py
- unicorn/py/unicorn_backend/model_runner_2.py
- unicorn/tests/py/integration/unicorn_backend/model_runner_2_test.py
- unicorn/tests/py/unit/unicorn_backend/date_time_utils_test.py
- unicorn/tests/py/unit/unicorn_backend/model_runner_2_test.py
CC @marionleborgne, @ywcui1990 
UNI-316 Implemented date_time_utils.py in unicorn_backend for supplementing datetime.strptime() with capability to parse the timezone.
UNI-316 Implemented unit tests for date_time_utils.py in unicorn_backend.
UNI-316 Implemented integration test for model_runner_2 that feeds timestamps with timezone offset.
UNI-316 Fixed up python strftime/strptime formats in js/config/momentjs_to_datetime_strptime.json.
> UNI-316 Implemented support for timezone parsing in unicorn and integrated into model_runner_2

- imbu/train_nlp_models.sh
This script builds new NLP models, trains them with a common cache, and saves them (serialized, ready for Imbu).
Relies on [nupic.research #464](https://github.com/numenta/nupic.research/pull/464).
@oxtopus please review
> IMBU-97 models training script

- unicorn/py/unicorn_backend/model_runner_2.py
- unicorn/py/unicorn_backend/param_finder_runner.py
CC @marionleborgne @ywcui1990 
- UNI-326 Use unicorn_backend.date_time_utils.parseDatetime instead of datetime.strptime in param_finder_runner.py
- Also fix several pylint warnings concerning unused imports and relative imports.
> UNI-326 Use unicorn_backend.date_time_utils.parseDatetime instead of datetime.strptime in param_finder_runner.py

- unicorn/js/browser/app.js
- unicorn/js/browser/lib/Unicorn/ConfigClient.js
- unicorn/js/browser/lib/Unicorn/DatabaseClient.js
- unicorn/js/browser/lib/Unicorn/FileClient.js
- unicorn/js/main/ConfigService.js
- unicorn/js/main/DatabaseService.js
- unicorn/js/main/FileService.js
- unicorn/js/main/index.js
- unicorn/tests/js/unit/services/DatabaseService_test.js
- unicorn/tests/js/unit/services/FileService_test.js
- unicorn/webpack.config.babel.js
Convert `main` process services into singletons created in the `main` process and accessed via `remote` by the `renderer` process.
@marionleborgne, @brev  Please review
> Convert services into singletons created in the `main` process only

- unicorn/README.md
- unicorn/js/main/ModelService.js
- unicorn/js/main/ParamFinderService.js
- unicorn/package.json
- unicorn/py/MANIFEST.in
- unicorn/py/requirements.txt
- unicorn/py/setup.py
This PR should replace #662 and #663.
Now `unicorn_backend` package is installed automatically into `portable_python` node module
If you have `portable_python` already installed you can use `npm run install:backend` to install the `unicorn_backend` package only.
Please review
@vitaly-krugl @marionleborgne @oxtopus
> Install 'unicorn_backend' package into 'portable_python' module

- unicorn/package.json
@marionleborgne, @brev 
This should fix the installation issues we had with `npm install` for `portable_python`.
CC: @oxtopus
> Fix installation using new ci build

- imbu/requirements.txt
@lscheinkman this allows me to install imbu on El Capitan. Is there a reason we specify v2.0.4?
> Update uwsgi req for imbu on osx 10.11

- taurus/conf/nginx-taurus.conf
- taurus/conf/supervisord.conf
CC @oxtopus 
This PR is in response to nginx failure issue reported on nupic@lists.numenta.org by vannroath
> Reduce taurus nginx and uwsgi listen queue sizes to 128 to match the default net.core.somaxconn on linux.

- unicorn/.gitignore
- unicorn/.istanbul.yml
- unicorn/README.md
- unicorn/package.json
Add code coverage reporting for JS unit and integration tests, .js and .jsx files.
`npm run test:coverage`
Ready for review @lscheinkman @marionleborgne
> Add code coverage reporting

- taurus.metric_collectors/tests/unit/xignite_stock_agent_test.py
CC @scottpurdy @oxtopus 
This happened after the graceful-update-testing-taurus-servers pipeline ran and failed, leaving the metric collectors in hot standby mode.
> Fix failure of XigniteStockAgentTestCase.testForwardAfterHours unit test when executed while metric collectors are in hot_standby mode

- taurus/requirements.txt
CC @scottpurdy @oxtopus 
Switching to uwsgi 2.0.12. The old 2.0.4 build fails on OS X 10.11 (undeclared SOL_TCP compiler error). See https://github.com/unbit/uwsgi/issues/1056.
I validated this change via http://jenkins-master.numenta.com/job/refresh-taurus-servers/251/.
Note that I still get a failure with 2.0.12 on OS X 10.11.4 when installging uwsgi indirectly via `python setup.py develop --user` from taurus (unable to write to a python system directory). However, `pip install uwsgi=2.0.12 --user` succeeds.
> Fix osx taurus install failure of uwsgi 2.0.4 by switching to uwsgi 2.0.12

- unicorn/app/browser/assets/styles/index.css
- unicorn/app/browser/components/LeftNav.jsx
- unicorn/app/browser/components/Logo.jsx
- unicorn/app/browser/components/Main.jsx
The experience of scrolling the sidebar is now identical to the experience of scrolling the charts.
The changes:
- You can now scroll the sidebar. It scrolls independently of the chart area.
- The scrollbar is positioned correctly. I had to work around a Chromium bug.
- The scrollbars are the same color. Previously the scrollbar in the charts area
was white because the operating system chose that color based on the
background color. The background color is a gradient, which causes the OS to
be weird and choose white (even though it chooses black if you use either
gradient endpoint as a solid-colored background). Now that the scrollbar lives in
a child element, this no longer happens. This is all a little bit goofy.
Additionally, the app no longer bounces up and down when you scroll to the …
> UNI-386: Make sidebar scrollable. Polish the scrolling experience.

- unicorn/app/browser/components/Chart.jsx
- unicorn/app/browser/components/ModelData.jsx
- unicorn/app/browser/lib/Dygraphs/AxesCustomLabelsUnderlay.js
- unicorn/app/browser/stores/MetricDataStore.js
- unicorn/app/browser/stores/ModelDataStore.js
- unicorn/app/main/DatabaseService.js
- unicorn/app/main/FileService.js
- unicorn/app/main/TimeAggregator.js
- unicorn/app/main/generateId.js
- unicorn/app/main/index.js
- unicorn/tests/js/integration/services/DatabaseService_test.js
When we add a file to the database, we currently parse the string as if it's in the current time zone. Then we save this parsed timestamp's Unix time. For nonexistent times like 2015-03-08 02:30:00 GMT-0800, we save the UTC Unix time for 2015-03-08 03:30:00 GMT-0800. So multiple data points are saved for this timestamp, because the actual 3:30am datum is also parsed as 3:30am.
The chart retrieves this Unix time from the database and formats it as the current time zone, then displays it. So the Unix time remains constant throughout this whole process, it just matters how we parse the initial string.
> UNI-334: Fix daylight savings. Assume UTC.

- unicorn/py/unicorn_backend/model_runner_2.py
- unicorn/tests/py/integration/unicorn_backend/model_runner_2_test.py
1. Add logging.NullHandler to the root logger in model_runner_2 to make sure that python logging won't implicitly add the default StreamHandler when some code logs via logging.debug, logging.info, etc.
2. Un-skip integration test `testModelRunnerFailsWithInvalidInputRecord`.
3. Fix several pylint warnings
> UNI-434 Fix unwanted logging message on stderr in unicorn model_runner_2

- unicorn/py/unicorn_backend/param_finder.py
- unicorn/tests/py/unit/unicorn_backend/param_finder_test.py
Summary
* Improve peak detection algorithm in paramFinder. The paramFinder now recommends to use timeOfDay encoder for VonAnalytics data. 
* Implement a long (20 weeks) cut off on time scale for wavelet analysis
* 	Always use 'mean' aggregation unless for binary data
* Update paramFinder tests
> UNI-409 Improve peak detection algorithm in paramFinder

- unicorn/app/browser/components/Chart.jsx
- unicorn/app/browser/components/ModelData.jsx
The issue here was in `_overlayDataSeries`. It's using a `.forEach` and not always doing something with the `item`.
I already reworked the way we build up this data for another change: https://github.com/numenta/numenta-apps/pull/761 . It fixes the bug. We're still discussing that change, so this PR is just that one without the controversial parts.
> UNI-438 Bugfix: skipping many raw data points when merging with aggregated

- unicorn/app/browser/components/Chart.jsx
- unicorn/app/browser/components/ModelData.jsx
Disable interpolation when we detect a time gap in the data.
Add a simple initial heuristic for detecting gaps. Compute all the time-deltas, find the 75th percentile, and multiply it by a factor (currently 1.5). The result is the gap threshold. This heuristic will be easy to tweak now that it's in place.
We have to detect gaps in aggregated and unaggregated data independently, and then merge them. This was difficult to fit into the existing code, so I shuffled the way we compute the Dygraphs input data.
> UNI-424 Don't connect dots that are too far apart

- unicorn/app/browser/components/ModelData.jsx
We don't currently set the valueRange of the "show non-aggregated" data, so its y scale (which doesn't have a visualized axis) quietly changes based on the selected timestep range.
Instead of giving it its own valueRange, just unite with the aggregated data. Share a y scale. Arguably we'd want to draw a second y axis if we want two different y scales.
> UNI-423 Use a single y scale for aggregated and raw data

- htm-it-mobile/pipeline/requirements.txt
- htm.it/htm/it/app/repository/migrations/versions/000_3a7e06671df4_base_to_1.6.py
- htm.it/htm/it/app/repository/migrations/versions/001_2f1ee984f978_1.6_to_1.7.py
- htm.it/htm/it/app/repository/migrations/versions/002_3b26d099594d_fix_datetime_and_timestamp_defaults.py
- htm.it/htm/it/pipeline/requirements.txt
- htm.it/requirements.txt
- htm.it/setup.py
- htm.it/tests/py/integration/app/runtime/aggregator_metric_collection_test.py
- htmengine/README.md
- htmengine/htmengine/repository/schema.py
- htmengine/tests/support/skeleton-app/migrations/versions/000_57ab75d58038_initial_htmengine.py
- htmengine/tests/support/skeleton-app/migrations/versions/002_872a895b8e8_fix_datetime_and_timestamp_defaults.py
- infrastructure/ami-tools/packer-scripts/configure-htm-it-pipeline-centos7-ami
- infrastructure/requirements.txt
- install-htm-it-from-bare-centos7.sh
- taurus-mobile/pipeline/requirements.txt
- taurus/taurus/engine/repository/migrations/versions/000_57ab75d58038_initial_htmengine.py
- taurus/taurus/engine/repository/migrations/versions/001_1d2eddc43366_timestatmp_to_datetime.py
- taurus/taurus/engine/repository/migrations/versions/002_a60d03066072_fix_datetime_and_timestamp_defaults.py
Fixes #779 
Fix server defaults for DATETIME and TIMESTAMP columns in taurus.engine, because
0 ("0000-00-00 00:00:00") is deprecated as default for those colum types
as of mysql 5.7.8, and will fail with mysql installed with default config
Fix server defaults for DATETIME and TIMESTAMP columns in htm.it, because
0 ("0000-00-00 00:00:00") is deprecated as default for those colum types
as of mysql 5.7.8, and will fail with mysql installed with default config.
Point tests in app/runtime/aggregator_metric_collection_test.py that require running instances to
the us-west-2 region, since we have no more running test EC2 instances in us-east-1
Fix default in instance_status_history.timestamp column of the htmengine's sleleton-app database.
> ENG-105 Fix DATETIME and TIMESTAMP mysql column defaults to work with MySQL 5.7.8+

- unicorn/app/browser/components/Chart.jsx
- unicorn/app/browser/components/ModelData.jsx
- unicorn/app/browser/lib/Dygraphs/AnomalyBarChartUnderlay.js
- unicorn/app/browser/lib/Dygraphs/CustomDygraph.js
Calculating in terms of "pointsPerBar" only works in some cases. It doesn't always work, e.g if there are gaps in the time series.
The new way of thinking: Split the timeline into equal-width buckets, based on the zoom level, and draw 0 or 1 anomaly bars per bucket.
This solves the general problem of collapsing anomaly bars into each other. For example, previously with non-aggregated data the anomaly bars would sometimes collide. Now they'll collapse into each other rather than collide.
@marionleborgne @lscheinkman 
This doesn't solve:
- Dygraphs doesn't let us set a "zoom limit", so on small data sets, you can zoom in further than we'd like users to zoom in.
- We might be able to solve this by adding another feature to Dygraphs via our new CustomDygraphs class.
- Or we could have our …
> Zooming: don't assume equally spaced data

- unicorn/app/browser/lib/Dygraphs/RangeSelectorBarChartPlugin.js
This adds support for irregularly-spaced data.
cc @marionleborgne
> Compute probationary width from timestamps, not indices

- unicorn/app/browser/components/ModelData.jsx
Before this change, the experience of running a model was different based on whether the model was aggregated. The time navigation bar would sometimes stay constant with the selection moving across it. Other times we would add timestamps of model results to the time navigation bar as they arrived. Now we always do the latter.
> Always use model result timestamps in navbar

- unicorn/app/browser/actions/StartModel.js
- unicorn/app/browser/lib/Constants.js
- unicorn/app/browser/stores/MetricStore.js
Problem 
* The HTM Settings at the bottom of the model summary dialog were incorrect. Except after you refresh the app.
Solution:
* This is happened because the DB was updated but not the metricStore - when the model is started.
* The fix consisted in dispatching an action to update the metricStore with param finder results for the specific model/metric that is started.
cc @mrcslws @lscheinkman
> Fix model results summary

- unicorn/app/package.json
- unicorn/scripts/OSX/build-python.sh
- unicorn/webpack.config.babel.js
@marionleborgne Here are the new DMG file size
```
125M	HTM Studio-0.0.1-mac.zip
107M	HTM Studio-0.0.1.dmg
```
The application size is still large but it was reduced by 300M:
```
348M	HTM Studio.app
```
To reduce the application size further we would need to dig deeper into electron's and python's dependencies. 
Here is `electron` dependency size:
```
106M	HTM Studio.app/Contents/Frameworks
```
Here are the top 10 dependencies `node_modules` sizes:
```
136M	HTM Studio.app/Contents/Resources/app/node_modules/portable_python_darwin
13M	HTM Studio.app/Contents/Resources/app/node_modules/roboto-fontface
10M	HTM Studio.app/Contents/Resources/app/node_modules/dygraphs
9.7M	HTM Studio.app/Contents/Resources/app/node_modules/material-ui
7.6M	HTM …
```
> UNI-444: Shrink portable python distribution  

- unicorn/README.md
- unicorn/app/browser/about.html
- unicorn/app/main/MainMenu.js
- unicorn/app/package.json
Updated URLs:
* HTM Studio: http://numenta.com/htm-studio/
* EULA Terms: http://numenta.com/htm-studio/?terms=1
* Feedback Form: http://numenta.com/htm-studio/#feedback
* FAQ anchor: http://numenta.com/htm-studio/#faq
Other changes:
* Pull version number from `app/package.json`
* Updated behavior of "Learn More" submenu (points to http://numenta.com/htm-studio/)
* Removed "File" menu which did not work
* Versioning documentation
> Updated native menus

- unicorn/app/browser/components/Model.jsx
Removed the tooltips from the action buttons in the model in model.jsx. Bug was due to inheriting the title from the Card.
Please Review @marionleborgne @lscheinkman
> UNI-464 removes tooltips on model action buttons

- unicorn/py/requirements.txt
- unicorn/scripts/OSX/build-python.sh
UNI-481 Freeze nupic at 0.5.0 via unicorn/py/requirements.txt
UNI-481 Modify unicorn/scripts/OSX/build-python.sh to pick up nupic version from unicorn/py/requirements.txt, then get matching nupic.core commitish from the nupic sources of the required version.
> UNI-481 Freeze nupic at 0.5.0 via unicorn/py/requirements.txt and automate nupic.core commitish

- unicorn/app/browser/components/Chart.jsx
This change also fixes the following bug:
1. Unhide a model that has finished running
2. Click "show non-aggregated data"
RESULT:
The selected dateWindow jumps to the end
@marionleborgne Note the label behavior. Some example text is:
Let me know what you think.
> Show metric name in hover text, not just 'Value:'

- unicorn/README.md
- unicorn/app/browser/actions/AddShowModel.js
- unicorn/app/browser/actions/DeleteFile.js
- unicorn/app/browser/actions/DeleteModel.js
- unicorn/app/browser/actions/ExportModelResults.js
- unicorn/app/browser/actions/FileUpdate.js
- unicorn/app/browser/actions/FileUpload.js
- unicorn/app/browser/actions/FileValidate.js
- unicorn/app/browser/actions/HideCreateModelDialog.js
- unicorn/app/browser/actions/HideFileDetails.js
- unicorn/app/browser/actions/HideModel.js
- unicorn/app/browser/actions/ModelError.js
- unicorn/app/browser/actions/OverrideParamFinderResults.js
- unicorn/app/browser/actions/ParamFinderError.js
- unicorn/app/browser/actions/ShowCreateModelDialog.js
- unicorn/app/browser/actions/ShowFileDetails.js
- unicorn/app/browser/actions/ShowModel.js
- unicorn/app/browser/actions/StartApplication.js
- unicorn/app/browser/actions/StartModel.js
- unicorn/app/browser/actions/StartParamFinder.js
- unicorn/app/browser/actions/StopModel.js
- unicorn/app/browser/actions/StopParamFinder.js
- unicorn/app/browser/actions/ToggleAggregateData.js
- unicorn/app/browser/entry.js
- unicorn/app/browser/index.html
- unicorn/app/browser/lib/Analytics/GoogleAnalytics.js
- unicorn/app/browser/lib/Fluxible/HTMStudioPlugin.js
- unicorn/app/package.json
- unicorn/webpack.config.babel.js
Use "Google Analytics" to collect usage data, currently tracking most 'React' actions.
- Based on Google Analytics [Measurement Protocol]( https://developers.google.com/analytics/devguides/collection/protocol/v1/). 
- Works offline by caching events in the browser's [indexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) store.
- In development mode the events are not stored but can be viewed in the debugger
- In production mode a real Google Analytics tracking ID must be provided, see `README`.
@marionleborgne Please Review
CC: @vitaly-krugl
> UNI-362: Add support for Google Analytics

- unicorn/app/browser/components/ModelData.jsx
Previously, the shouldComponentUpdate method handled charts that had models, but it would always re-render the chart when it didn't have any model results.
Now chart removal is pretty fast, but not instant, because re-rendering the entire file list still takes some time.
Here are some quick numbers. There's a margin of error, but it shows the order of magnitude improvement.
**Before this change**
Add first chart: ~360ms
Remove first chart: ~200ms
Add 5th chart: ~1450ms
Remove 5th chart: ~1300ms
**After this change**
Add first chart: ~360ms
Remove first chart: ~115ms
Add 5th chart: ~400ms
Remove 5th chart: ~200ms
> UNI-500 Re-rendering: handle the "no model results" case

- unicorn/README.md
- unicorn/package.json
@marionleborgne per your request.
To remove your cached version of `portable_python` run the following command:
```shel
npm run clean:portable_python:osx
```
This will force the new version of python to be downloaded from the latest successful build like before.
> UNI-502: Add script to remove cached `portable_python`

- unicorn/app/browser/about.html
- unicorn/app/main/MainMenu.js
- unicorn/app/package.json
Fixes: 
* UNI-490 HTM Studio drop down menus have meaningless/ useless items
* UNI-491 Link in about box should say "Terms and Conditions" not "License"
* UNI-489 About box has extraneous title after clicking license link
* UNI-498 add a "Report bug" submenu 
And should help for the windows build. @oxtopus let me know if this works for you.
> UNI-490: HTM Studio drop down menus 

- unicorn/app/config/momentjs_to_datetime_strptime.json
This was already being tested in unicorn_backed, but none of it is tested on the JS side.
Marion recommended to defer JS-side tests, since this is so well tested in unicorn_backend, in favor of higher-priority issues.
> UNI-495 Enable YYYY-MM-DD and YYYY/MM/DD date formats.

- unicorn/app/main/MainMenu.js
Restore JS Development tools menu option when launching the app in development mode, either via `npm run dev` or when the `NODE_ENV` variable is set to 'development'
CC: @marionleborgne, @andrewmalta13
> UNI-490: Restore development tools in development mode

- unicorn/app/browser/actions/StopApplication.js
- unicorn/app/browser/entry.js
- unicorn/app/browser/lib/Constants.js
- unicorn/app/browser/stores/ModelDataStore.js
The stop model action gets called whenever a model ends, so it's the wrong place to cancel any pending queries.
With super-small datasets, we were seeing 0 results appear.
Thanks @marionleborgne for catching this.
> Bugfix: We're cancelling model data queries too often

- unicorn/app/browser/actions/ModelError.js
- unicorn/app/browser/actions/ParamFinderError.js
- unicorn/app/browser/lib/HTMStudio/ModelClient.js
- unicorn/app/browser/lib/HTMStudio/ParamFinderClient.js
@marionleborgne This PR fixes messages being logged as  'UNKNOWN_MODEL_ERROR' and 'UNKOWN_PARAM_FINDER_ERROR' when creating the models. Now it logs the real error name.
We should fix the real error on a separate PR.
> UNI-518: Fix error messages when creating models

- unicorn/app/main/index.js
@marionleborgne this should make the app single instance on Windows and Mac preventing database lock errors when trying to relaunch the app.
CC: @cbaranski
> UNI-558: Make app single instance

- unicorn/app/main/AutoUpdate.js
@marionleborgne, @cbaranski 
There should be a desktop and start menu shortcuts once the app is done installing.
> UNI-542: Fix call to 'Update.exe' with quoted parameters 

- unicorn/osx/Vagrantfile
This should speed up OSX builds
CC: @oxtopus
> Use virtual box linked clone feature instead of reimporting hard-disk

- unicorn/app/browser/stores/ModelDataStore.js
- unicorn/app/browser/stores/ModelStore.js
This change fixes two similar bugs. When you rapidly click the show/hide checkbox, events can happen in an unexpected order. Now we detect this scenario in ModelDataStore and ModelStore.
@marionleborgne @lscheinkman
> UNI-578 Handle rapid checkbox clicking

- unicorn/app/package.json
@cbaranski made the description "HTM Studio". Instead of "Numenta HTM Studio Cross-platform HTM Example Desktop Application"
> updated app description

- unicorn/app/browser/components/Chart.jsx
This used to work. It broke when I made the big d3 change, commit 48799da40e296b4bec4507c9127e622b2fa8f0d0
Dygraphs uses the "highlightCircleSize" parameter to choose the size of these dots. We no longer use Dygraphs highlight dots, so I disabled them. This had unintended consequences.
The fix: give the circles some size, and disable them via a callback.
@marionleborgne
> UNI-583 When a point has gaps on both sides, show a dot

- unicorn/app/browser/components/ModelData.jsx
The gap detection heuristic was too agressive and this was leading to a couple of datasets being represented as a cloud of dots. This PR fixes it: `water_treatment_log.csv` metrics are now represented as continuous series while the `JAO_apple_*.csv` still shows gaps between daily recordings. See screenshot below:
@mrcslws please review
> Making the gap detection a little less aggressive and more robust to outliers

- unicorn/app/browser/components/Chart.jsx
The y scale was broken when there was only one point on-screen.
Thanks @marionleborgne for pointing out the bug.
> y-scaling: handle case where min == max

- htmengine/htmengine/model_swapper/model_swapper_interface.py
- htmengine/tests/unit/model_swapper/model_swapper_interface_test.py
Fixes #891 
The goal of this PR is narrowly focused on improving the existing argument check and providing slightly more diagnostic info when the check fails, such as the initial failure described in https://discourse.numenta.org/t/my-installation-suddenly-failed-with-asertionerror-message/1389.
> Make anomalyScore type check more general and add type of the offending object to the assertion message when typecheck of anomaly score fails

- htmengine/htmengine/model_swapper/model_swapper_interface.py
Reported by licensee and in https://discourse.numenta.org/t/problem-running-htmengine-skeleton-app/1403.
The issue occurs when the resulting anomalyScore is of type `numpy.float32` or `numpy.float16`. E.g.,
```
>>> json.dumps(numpy.float(1.0))
'1.0'
>>> json.dumps(numpy.float32(1.0))
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 243, in dumps
return _default_encoder.encode(obj)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 207, in encode
chunks = self.iterencode(o, _one_shot=True)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 270, in iterencode
return …
```
> Cast anomalyScore to float to work around json serialization issue

- unicorn/README.md
Small PR to remove the obsolete warning in the README.
> Remove "under heavy development" warning
