numenta/numenta-apps

taurus.metric_collectors/README.md
taurus/README.md

Updated README's to new open source repo

---

grok-mobile/run_pipeline

@lscheinkman @unixorn please review

Expand try/except block to ensure that failures in the pipeline get handled properly and instances are stopped/terminated appropriately

---

mobile-core/android/src/main/java/com/numenta/core/app/GrokApplication.java
taurus-mobile/android/app/src/androidTest/java/com/numenta/taurus/test/unit/MetricListAdapterTest.java

TAUR-1114: Add default thread pool to be used by unit tests #send-for-review

---

CONTRIBUTING.md

@rhyolight for real this time to address #13

Add CONTRIBUTING.md back after I accidentally reverted it

---

grok-mobile/README.md
grok-mobile/android/app/build.gradle
grok-mobile/run_pipeline
mobile-core/android/common.gradle
taurus-mobile/README.md
taurus-mobile/android/app/build.gradle
taurus-mobile/run_pipeline

@jcasner Please review. 
I've also updated the `jenkins` configuration adding the appropriate `INITIAL_VERSION_CODE ` environment variable to both pipelines

Add option to change initial version code value.

---

htmengine/.gitignore
htmengine/README.md
nta.utils/.gitignore
requirements.txt

- Updated HTM Engine README
- Removed requirements.txt at root dir (fixes #31)
- Updated .gitignores

Minor cleanup

---

taurus-mobile/tests/behavioral/TaurusMobileApp/src/test/java/taurustest/TaurusMobileAppTest.java

In this PR, for taurus-android appium tests, I have added dependencies for executing methods. Using this we can reduce the time duration required for appium tests.
@jcasner @unixorn @lscheinkman @shantanoo ,  Please Review.

TAUR-1238-Mobile-pipeline-saucelabs-issue

---

taurus-mobile/tests/behavioral/TaurusMobileApp/src/test/java/taurustest/TaurusMobileAppTest.java

- Removing capability for appium-version.
- Sauce lab is not supporting appium version 1.3.1. So removing version from capabilities. 
@shantanoo Please Review.

HOT-FIX-TAUR-1238-Mobile-pipeline-saucelabs-issue

---

docker-build-all.sh
taurus.metric_collectors/Dockerfile
taurus.metric_collectors/docker/taurus.metric_collectors/run-taurus.metric_collectors.sh
taurus.metric_collectors/requirements.txt
taurus/Dockerfile
taurus/docker/README.md

Docker configuration for taurus.metric_collectors

---

taurus/taurus/engine/runtime/dynamodb/dynamodb_service.py

TAUR-1137 Gracefully filter tweet text

---

taurus/external/dynamodb_test_tool/Dockerfile

@oxtopus Please review
I've updated the dynamodb test tool to download the latest version from amazon and share the sqlite database.

Update dynamodb test tool docker file to download the latest version

---

infrastructure/infrastructure/utilities/ec2.py

@jaredweiss this fixes the error you ran into, please CR.

InstanceNotFoundError exception wasn't being imported

---

htmengine/setup.py
infrastructure/ami-tools/packer-scripts/configure-grok-pipeline-ami
infrastructure/infrastructure/utilities/nupic/build_commands.py

TAUR-1217 update some nupic build stuff and some packer commands

---

grok/grok/pipeline/src/bake_ami.py

Can't believe I missed that the domain was old. Thanks for the catch, @jcasner

TAUR-990 Fix domain in bucket name

---

infrastructure/saltcellar/numenta-python/init.sls

@unixorn, @jcasner please review.

Installing numpy 1.9.2 version

---

taurus-mobile/android/app/src/androidTest/java/com/numenta/taurus/test/unit/MetricListAdapterTest.java

@jcasner Please review.
This should fix 'MetricListAdapterTest'.
See #64

Fix test after removing test specific API from GrokApplication

---

grok/pavement.py
htmengine/setup.py
install-grok.sh
install-taurus.sh

@jcasner Seems to work for me with an instance started with internal `nta-start-instance` tool.

Include numpy in `setup_requires` (and `install_requires`)

---

infrastructure/saltcellar/motd/files/20-banner.motd

Add kernel version to /etc/motd

---

install-infrastructure.sh
install-taurus-metric-collectors.sh
install-taurus.sh

Update installation files

---

taurus-mobile/android/app/src/main/java/com/numenta/taurus/twitter/TwitterDetailActivity.java
taurus-mobile/android/app/src/main/java/com/numenta/taurus/twitter/TwitterListAdapter.java
taurus-mobile/android/app/src/main/res/layout/activity_twitter_detail.xml
taurus-mobile/android/app/src/main/res/values/strings.xml

TAUR-1260: Add "loading" message when loading more than 500 tweets

---

README.md

Fixes https://github.com/numenta/numenta-apps/issues/83

adding taurus.monitoring to README

---

infrastructure/ami-tools/.gitignore
infrastructure/ami-tools/Rakefile
infrastructure/ami-tools/ami-configurations/centos6.json
infrastructure/ami-tools/ami-configurations/infrastructure-base-256gb.json
infrastructure/ami-tools/ami-configurations/infrastructure-base.json
infrastructure/ami-tools/packer-scripts/cleanup-image
infrastructure/ami-tools/packer-scripts/cleanup-infrastructure-ami
infrastructure/ami-tools/packer-scripts/configure-infrastructure-ami
infrastructure/ami-tools/packer-scripts/install-devtools
infrastructure/ami-tools/packer-scripts/install-epel-repo-6.5

* Ensure kernel is up to date
* Fix error in `infrastructure/ami-tools/packer-scripts/install-epel-repo-6.5`
* Install devtools during AMI bake to save time during pipeline runs
* Ensure yum update is run during AMI bakes
* infrastructure and infrastructure 256gb packer configurations now connect to salt master instead of using salt in local mode

TAUR-1261 Updates to base CentOS setup

---

taurus-mobile/android/app/src/main/java/com/numenta/taurus/data/Tweet.java
taurus-mobile/android/app/src/main/java/com/numenta/taurus/twitter/TwitterDetailActivity.java
taurus-mobile/android/app/src/main/res/drawable/twitter_list_divider.xml
taurus-mobile/android/app/src/main/res/layout/twitter_item.xml

TAUR-1262: Add space between items and thicker divider to condensed twitter list view

---

taurus-mobile/android/app/src/main/java/com/numenta/taurus/metric/MetricListAdapter.java

TAUR-1252: Fix "BadTokenException" when the background task is canceled #send-for-review

---

taurus-mobile/android/app/src/main/java/com/numenta/taurus/data/Tweet.java
taurus-mobile/android/app/src/test/java/com/numenta/taurus/test/unit/TweetTest.java

@jcasner Please review.
This should fix `taurus-mobile-product-pipeline`

TAUR-1262: Fix tweet tests and rules

---

taurus-mobile/android/app/src/main/java/com/numenta/taurus/twitter/TwitterDetailActivity.java

TAUR-1262: Remove empty tweets from the list

---

taurus/pipeline/scripts/README.md
taurus/pipeline/scripts/initialize-remote-taurus-servers.sh
taurus/pipeline/scripts/refresh-remote-taurus-servers.sh
taurus/pipeline/scripts/update-remote-taurus-servers.sh

These bash scripts will form the basis for an automated CI pipeline

TAUR-851 Helper scripts for automating taurus code updates

---

grok/tests/py/ami/test_grok.py
infrastructure/saltcellar/logrotate/files/groklog_rotator
infrastructure/saltcellar/logrotate/init.sls

* Add groklog_rotator
* Update grok AMI test to confirm presence of groklog_rotator

Somehow we missed copying groklog_rotator when we did the chef->salt conversion

---

infrastructure/saltcellar/logrotate/files/groklog_rotator

In `while` loop, `fileList` was updated in each iteration. Changed it to `for` loop.

Converted while loop to for

---

mobile-core/android/build.gradle
taurus-mobile/Dockerfile
taurus-mobile/android/app/build.gradle
taurus-mobile/android/app/src/androidTest/java/com/numenta/taurus/test/integration/TaurusClientTest.java
taurus-mobile/android/app/src/androidTest/java/com/numenta/taurus/test/unit/MetricListAdapterTest.java

... and re-enable dynamodb integration test
@jcasner  Please Review
@shantanoo This PR should unblock TAUR-867

TAUR-1265: Refactor pure JUnit4 tests to AndroidJUnitRunner

---

grok/grok/app/webservices/webapp.py

TAUR-1292 fall back to git rev-parse if no grok.sha file exists

---

taurus-mobile/run_pipeline

TAUR-1265: Replace legacy SERVER_URL from the pipeline script with local dynamodb tool URL

---

install-grok-from-bare-centos7.sh

@shantanoo @unixorn please review

Add install helper for centos 7

---

pipeline_controller

Remove optional "SERVER_URL" parameter

---

infrastructure/saltcellar/numenta-python/init.sls

@oxtopus this should get the right version of setuptools for you.  Not sure why we were version locked to such an old version.

TAUR-1300 update setuptools version

---

infrastructure/ami-tools/packer-scripts/configure-grok-pipeline-ami
install-grok-from-bare-centos7.sh

Update with feedback from previous pull request

---

grok/grok/test_utils/app/test_case_base.py
grok/tests/py/integration/app/runtime/metric_collector_int_test.py

re: https://jira.numenta.com/browse/TAUR-1285

Taur 1285 test start and stop metric collector

---

grok/grok/app/adapters/datasource/cloudwatch/aws_autoscaling_group.py
grok/grok/app/adapters/datasource/cloudwatch/aws_dynamodb_table.py
grok/grok/app/adapters/datasource/cloudwatch/aws_ebs_volume.py
grok/grok/app/adapters/datasource/cloudwatch/aws_elb_load_balancer.py
grok/grok/app/adapters/datasource/cloudwatch/aws_opsworks_stack.py
grok/grok/app/adapters/datasource/cloudwatch/aws_rds_dbinstance.py
grok/grok/app/adapters/datasource/cloudwatch/aws_redshift_cluster.py
grok/grok/app/adapters/datasource/cloudwatch/aws_sns_topic.py
grok/grok/app/adapters/datasource/cloudwatch/aws_sqs_queue.py

TAUR-1296 fix some issues with pylint in grok/app/adapters

---

grok/tests/py/integration/app/result_quality_test.py

@scottpurdy: I am not too happy with a change like this as some of the individual results for one of the tests seem a lot worse than in the past. I am submitting the PR to help with discussion.

TAUR-873 Retune expected results to make result-quality-test pass.

---

grok/grok/app/adapters/datasource/cloudwatch/aws_opsworks_stack.py
grok/grok/app/aws/cloudwatch_utils.py

TAUR-1320 Fixup function signature to match super class

---

nta.utils/requirements.txt
taurus/requirements.txt

TAUR-1319 ensure the correct version of mock gets installed for Taurus

---

taurus-mobile/android/app/src/main/java/com/numenta/taurus/service/TaurusNotificationService.java

TAUR-1245: Make sure to apply log scale matching the UI behavior before firing notification

---

infrastructure/saltcellar/rabbitmq/init.sls

@unixorn please review
@oxtopus FYI

TAUR-1272 update rabbitmq-server version to ensure version 3.5.3 gets installed

---

taurus-mobile/android/app/src/main/java/com/numenta/taurus/twitter/TwitterDetailActivity.java
taurus-mobile/android/app/src/test/java/com/numenta/taurus/test/unit/TweetTest.java

@jcasner It looks like TAUR-1294 is obsolete but I added a test just in case. Please review

TAUR-1294: Add test for sort order #send-for-review

---

infrastructure/saltcellar/rabbitmq/init.sls

@unixorn @shantanoo please review

TAUR-1272 go back to using pkgrepo.managed

---

taurus-mobile/android/app/src/main/java/com/numenta/taurus/instance/InstanceDetailPageFragment.java

TAUR-1321: Collapse market hours when there is no anomaly after hours #send-for-review

---

infrastructure/saltcellar/rabbitmq/files/rabbitmqadmin
infrastructure/saltcellar/rabbitmq/init.sls

@oxtopus @unixorn please review

TAUR-851 TAUR-1272 Update rabbitmqadmin script and add taurus user to rabbit

---

infrastructure/saltcellar/rabbitmq/init.sls

@oxtopus @unixorn please review.  This is a hack until https://github.com/saltstack/salt/issues/25683 is resolved.

TAUR-851 switch to using cmd.run since there is a bug in salt

---

infrastructure/saltcellar/mysql/files/tests/test_local_mysqld.py
infrastructure/saltcellar/mysql/server.sls

Confirm that mysqld is enabled at boot and running.

TAUR-1279 Add agamotto tests for local mysqld

---

grok/requirements.txt
taurus.metric_collectors/requirements.txt
taurus/requirements.txt

re: https://jira.numenta.com/browse/TAUR-1337

TAUR-1337 Fixup supervisor version across the board to match

---

grok-mobile/android/app/build.gradle
grok-mobile/android/app/src/main/java/com/groksolutions/grok/mobile/annotation/AddAnnotationActivity.java
grok-mobile/android/app/src/main/java/com/groksolutions/grok/mobile/chart/AbstractAnomalyChartFragment.java
grok-mobile/android/app/src/main/res/layout/activity_add_annotation.xml
grok-mobile/android/app/src/main/res/layout/activity_annotation_list.xml
grok-mobile/android/app/src/main/res/layout/fragment_instance_detail_page.xml
grok-mobile/android/app/src/main/res/layout/fragment_metric_detail.xml
grok-mobile/android/build.gradle
grok-mobile/android/gradle/wrapper/gradle-wrapper.properties
taurus-mobile/android/build.gradle

TAUR-1120: Fix multiple NPE related to missing id in fragment layouts #send-for-review

---

taurus-mobile/android/app/src/main/java/com/numenta/taurus/instance/InstanceDetailPageFragment.java

TAUR-1334: Prevent collapsing during scroll

---

grok-mobile/run_pipeline

TAUR-1120: Fix mobile pipeline

---

taurus.metric_collectors/tests/integration/xignite_stock_agent_test.py
taurus/pipeline/scripts/initialize-remote-taurus-servers.sh
taurus/pipeline/scripts/refresh-remote-taurus-servers.sh
taurus/pipeline/scripts/update-remote-taurus-servers.sh
taurus/tests/integration/runtime/dynamodb/dynamodb_service_test.py

… to support pipeline wonkiness

User-specifiable git command and ssh args

---

taurus-mobile/android/app/src/main/java/com/numenta/taurus/metric/MetricListFragment.java
taurus-mobile/android/gradle/wrapper/gradle-wrapper.properties

TAUR-1333: Fix selecting twitter on collapsed view #send-for-review

---

infrastructure/ami-tools/boot-scripts/centos7/grokservices.service
infrastructure/ami-tools/boot-scripts/centos7/rabbitmq-server.service
infrastructure/ami-tools/packer-scripts/configure-grok-pipeline-centos7-ami

@shantanoo @unixorn please review
May need some more work based on my comments in TAUR-1349

TAUR-1349 complete AMI creation process

---

infrastructure/infrastructure/utilities/nupic/build_commands.py
infrastructure/infrastructure/utilities/nupic/run_pipeline

I removed NUPIC_CORE_BRANCH since it was redundant because we have the sha.
@jcasner

removed nupic core branch env var

---

grok/grok/pipeline/conf/config.yaml
grok/grok/pipeline/src/bake_ami.py
grok/grok/pipeline/src/run_grok_integration_tests.py
grok/grok/pipeline/src/run_unit_tests.py
grok/tests/ci/test_commands_xunit.txt
infrastructure/infrastructure/utilities/cli.py
infrastructure/infrastructure/utilities/grok_server.py

Currently, files are getting stepped on so results are incomplete. They're also in non-standard locations, making it difficult for jenkins to archive them. Updating to use a standard location and naming schema to ensure results are not overwritten

Update how we're saving test results

---

infrastructure/infrastructure/utilities/exceptions.py

Add PermissionsFailure exception

---

htmengine/README.md

CC @jcasner @oxtopus. I thought this was a good idea.

Added link to HTM skeleton app on HTM Engine README.

---

htmengine/README.md

Added tutorial code and video links to HTM Engine README.

---

taurus-mobile/android/app/src/main/java/com/numenta/taurus/instance/InstanceListActivity.java
taurus-mobile/android/app/src/main/java/com/numenta/taurus/twitter/TwitterDetailActivity.java

TAUR-1364: Prevent jitter when scrolling to the last twitter item

---

infrastructure/infrastructure/utilities/git.py
infrastructure/setup.py

Added clean and setRemoteURL functions per TAUR-1338 feedback.

TAUR-1338 Add more git helper functions

---

grok/grok/app/runtime/notification_service.py

TAUR-1368 Fixed stuck processing of notification queue in grok's notification service.
TAUR-1368 Fixed access to uninitialized local variable rowDatetime when no devices are configured.

TAUR-1368 Fixed stuck processing of notification queue in grok's notification service

---

grok-mobile/android/app/src/androidTest/java/com/groksolutions/grok/mobile/test/unit/MetricParserTests.java
grok-mobile/android/app/src/main/java/com/groksolutions/grok/mobile/service/MetricParser.java
mobile-core/android/src/main/java/com/numenta/core/data/Metric.java
mobile-core/android/src/main/java/com/numenta/core/utils/NotificationUtils.java

TAUR-1381: Fix unknown metric unit #send-for-review

---

grok-mobile/android/app/src/androidTest/java/com/groksolutions/grok/mobile/test/unit/MetricParserTests.java
grok-mobile/android/app/src/main/java/com/groksolutions/grok/mobile/data/GrokDataFactoryImpl.java
grok-mobile/android/app/src/main/java/com/groksolutions/grok/mobile/data/GrokDatabase.java
mobile-core/android/src/main/java/com/numenta/core/data/Metric.java

@jcasner This PR should fix both mobile builds (460 and 531)

TAUR-1381: Initialize metric unit value from custom grok factory

---

htmengine/requirements.txt
unicorn/backend/requirements.txt

TAUR-1394 revert to nupic==0.2.6 until nupic release issues are resolved #send-for-review

---

infrastructure/infrastructure/utilities/cli.py

Passing the error message string to next exception.

---

htmengine/requirements.txt
unicorn/backend/requirements.txt

Complete AGPL conversion by using NuPIC 0.2.11 release

---

grok-mobile/run_pipeline
grok/behavioral_tests_driver
grok/grok/pipeline/scripts/rpm-creator/rpm-creator.py
grok/grok/pipeline/src/bake_ami.py
grok/grok/pipeline/src/build.py
grok/grok/pipeline/src/grok-pipeline
grok/grok/pipeline/src/manifest.py
grok/grok/pipeline/src/package.py
grok/grok/pipeline/src/run_grok_integration_tests.py
grok/grok/pipeline/src/run_unit_tests.py
grok/grok/pipeline/src/sync_yum_repo_s3.py
infrastructure/ami-tools/create-grok-manifest
infrastructure/infrastructure/create-numenta-rpm
infrastructure/infrastructure/utilities/infrastructure-rpm-pipeline/run_pipeline
infrastructure/infrastructure/utilities/janitor_pipeline/janitor_ec2.py
infrastructure/saltcellar/grok-plumbing/files/install-grok-packages
pipeline_controller
taurus-mobile/run_pipeline

TAUR-1363 HOTFIX for invalidated imports

---

htmengine/tests/integration/model_swapper/model_swapper_e2e_test.py
unicorn/backend/setup.py
unicorn/backend/unicorn_backend/model_runner.py
unicorn/tests/py/integration/model_runner_test.py

ENG-25 Implement dummy anomaly likelihood output from unicorn_backend.model_runner
ENG-25 Implemented basic integration tests for unicorn_backend.model_runner

ENG-25 Implement dummy anomaly likelihood output from backend model runner

---

unicorn/backend/unicorn_backend/model_runner.py
unicorn/tests/py/integration/model_runner_test.py

Address @shantanoo's code review feedback from #230

ENG-25 Code review feedback fixes.

---

unicorn/README.md
unicorn/frontend/browser/app.js
unicorn/frontend/main.js
unicorn/package.json

UNI-144 #comment Setup IPC stream between Electron Main process and Renderer
Process. Create 3 demo channels on stream, one each for Model Client/Server,
File Client/Server, and Database Client/Server. Small bits of example code left
on both sides for those future JIRAs, I'll leave notes on them. Added new
package. Update README docs and @TODOs.
Includes work for UNI-146.
FYI @jcasner @lscheinkman @marionleborgne

UNI-144 #comment Setup IPC stream between Electron Main process and Renderer

---

infrastructure/saltcellar/numenta-python/init.sls

Update pip to 7.1.1

---

imbu/.babelrc
imbu/.eslintrc
imbu/.gitignore
imbu/LICENSE.txt
imbu/README.md
imbu/engine/README.md
imbu/gui/browser/actions/search-clear.js
imbu/gui/browser/actions/search-query.js
imbu/gui/browser/app.js
imbu/gui/browser/components/main.jsx
imbu/gui/browser/components/search-history.jsx
imbu/gui/browser/components/search-results.jsx
imbu/gui/browser/components/search.jsx
imbu/gui/browser/css/main.css
imbu/gui/browser/index.html
imbu/gui/browser/stores/search.js
imbu/gui/loader.js
imbu/gui/main.js
imbu/gulpfile.babel.js
imbu/package.json
imbu/requirements.txt

@brev  Please review
CC: @jcasner

IMBU-5: Initial wireframe

---

unicorn/README.md
unicorn/package.json

UNI-143 #comment Clear out some of my earlier general @TODOs.
Mostly regarding dox and debugging.
Random changes, FYI @lscheinkman @jcasner @marionleborgne.

UNI-143 #comment Clear out some of my earlier general @TODOs.

---

infrastructure/saltcellar/numenta-python/init.sls

Bump pip version to 7.1.2

---

infrastructure/infrastructure/utilities/path.py

TAUR-1338 Add a mode argument to mkdirp (default 0755)

---

nta.utils/nta/utils/tools/get_supervisord_state.py
nta.utils/setup.py
taurus/pipeline/scripts/initialize-remote-taurus-servers.sh
taurus/pipeline/scripts/refresh-remote-taurus-servers.sh
taurus/pipeline/scripts/update-remote-taurus-servers.sh

ENG-37 Implement conditional unit/integration test execution in refresh-remote-taurus-servers.sh based on optional arg: -t destructive-tests

ENG-37 Implement conditional unit/integration test execution in taurus pipeline scripts

---

grok-mobile/run_pipeline
grok/behavioral_tests_driver
grok/grok/pipeline/src/run_grok_integration_tests.py
grok/grok/pipeline/src/run_unit_tests.py
taurus-mobile/run_pipeline

TAUR 1369 Passing 'logger' parameter to getWorkspace function

---

imbu/.gitignore
imbu/README.md
imbu/conf/mime.types
imbu/conf/nginx-fluent.conf
imbu/conf/nginx-supervisord.conf
imbu/conf/nginx-uwsgi.conf
imbu/conf/supervisord.conf
imbu/engine/fluent_api.py
imbu/gui/browser/actions/search-query.js
imbu/requirements.txt
imbu/setup.py

@jcasner This is the web version. 
I have a small document with the extra steps needed to bring a demo server up using our internal salt roles.
FYI: @BoltzmannBrain, @unixorn

IMBU-5: Add web service configuration

---

infrastructure/infrastructure/utilities/nupic/build_commands.py

Add capnp install steps to pipeline.

---

install-taurus-monitoring
nta.utils/nta/utils/error_reporting.py
taurus.monitoring/taurus/monitoring/supervisord_monitor/supervisord_monitor.py

* Add install-taurus-monitoring script
* Add `--subjectPrefix` option so we can make the error message different for different machines (staging and production)

TAUR-1383 Add taurus monitoring install script and --subjectPrefix option

---

infrastructure/ami-tools/packer-scripts/configure-grok-pipeline-centos7-ami

@unixorn please review
FYI @oxtopus @scottpurdy

TAUR-1424 update version of rabbit in Grok

---

unicorn/.gitignore
unicorn/frontend/browser/app.js
unicorn/frontend/database/schema/Address.json
unicorn/frontend/database/schema/Person.json
unicorn/frontend/lib/DatabaseServer.js
unicorn/package.json

UNI-153 #comment Init DB schemas and validations.
FYI @marionleborgne @lscheinkman 
I'm porting old Grok/Taurus schema to JSON next.

UNI-153 #comment Init DB schemas and validations.

---

unicorn/frontend/browser/actions/ListMetrics.js
unicorn/frontend/browser/app.js
unicorn/frontend/browser/components/FileListComponent.jsx
unicorn/frontend/browser/components/Main.jsx
unicorn/frontend/lib/FileServer.js

@marionleborgne This PR should fix the warnings you saw.
CC: @brev

UNI-161: Use Promises to dispatch chained actions

---

infrastructure/infrastructure/utilities/ec2.py
infrastructure/setup.py

@jcasner @shantanoo, please CR

TAUR-1356 Add function to set/unset EC2 instance termination protection

---

unicorn/frontend/browser/components/FileList.jsx
unicorn/frontend/browser/components/Main.jsx

UNI-161: Copy 'LeftNav' style

---

unicorn/backend/requirements.txt
unicorn/backend/unicorn_backend/model_runner.py
unicorn/tests/py/integration/model_runner_test.py

@scottpurdy, please review _ModelRunner class changes to make sure it uses NuPIC's anomaly likelihood algorithm correctly.
IMPORTANT: this PR depends on a new release of nupic (0.2.12?) that will include the NuPIC PR https://github.com/numenta/nupic/pull/2535

ENG-26 Implement anomaly likelihood processing in unicorn backend.

---

infrastructure/saltcellar/aws-support/init.sls
infrastructure/saltcellar/devtools/init.sls
infrastructure/saltcellar/dotfiles/init.sls
infrastructure/saltcellar/grok-plumbing/init.sls
infrastructure/saltcellar/grok-plumbing/support-tools.sls
infrastructure/saltcellar/grok-plumbing/yumrepos.sls
infrastructure/saltcellar/motd/init.sls
infrastructure/saltcellar/nta-nucleus/files.sls
infrastructure/saltcellar/nta-nucleus/security.sls
infrastructure/saltcellar/nta-nucleus/services.sls
infrastructure/saltcellar/nta-nucleus/test-support.sls
infrastructure/saltcellar/nta-yum/init.sls
infrastructure/saltcellar/role-grok/install-grok.sls
infrastructure/saltcellar/role-grok/test-support.sls
infrastructure/saltcellar/saltsolo/init.sls
infrastructure/saltcellar/sudoers-setup/init.sls

Fixed permission for files/directories

---

unicorn/frontend/browser/components/Chart.jsx
unicorn/frontend/browser/components/FileList.jsx
unicorn/frontend/browser/components/Main.jsx
unicorn/package.json

UNI-163: Wrap dygraph in React Component

---

unicorn/frontend/browser/actions/FileUpload.js
unicorn/frontend/browser/components/FileList.jsx
unicorn/frontend/browser/components/FileListComponent.jsx
unicorn/frontend/browser/components/Main.jsx
unicorn/frontend/browser/stores/FileStore.js
unicorn/frontend/lib/FileServer.js

Uni 160 display uploaded file metrics in left menu

---

infrastructure/saltcellar/nta-nucleus/packages.sls

TAUR-1301 Removing git (git v1.x) as nta-git (git v2.x) package avaialble.

---

unicorn/frontend/browser/actions/AddModel.js
unicorn/frontend/browser/actions/DeleteModel.js
unicorn/frontend/browser/actions/ListModels.js
unicorn/frontend/browser/actions/ReceiveData.js
unicorn/frontend/browser/actions/StopModel.js
unicorn/frontend/browser/app.js
unicorn/frontend/browser/components/Chart.jsx
unicorn/frontend/browser/components/FileList.jsx
unicorn/frontend/browser/components/Main.jsx
unicorn/frontend/browser/components/Model.jsx
unicorn/frontend/browser/components/ModelData.jsx
unicorn/frontend/browser/components/ModelList.jsx
unicorn/frontend/browser/lib/ModelUtils.js
unicorn/frontend/browser/stores/ModelDataStore.js
unicorn/frontend/browser/stores/ModelStore.js

@brev Please review when you have a chance.
CC: @marionleborgne, @jcasner

UNI-162: Add model list to main page and connect actions to file list

---

taurus.metric_collectors/tests/deployment/README.md
taurus.metric_collectors/tests/deployment/health_check_test.py
taurus.metric_collectors/tests/deployment/resource_accessibility_test.py
taurus/pipeline/scripts/initialize-remote-taurus-servers.sh
taurus/pipeline/scripts/refresh-remote-taurus-servers.sh
taurus/pipeline/scripts/update-remote-taurus-servers.sh
taurus/tests/deployment/README.md
taurus/tests/deployment/health_check_test.py
taurus/tests/deployment/resource_accessibility_test.py

ENG-39 Implement baseline health check tests that check that all services are in the RUNNING state.
ENG-39 Share retry decorator configuration. Add license text and docstrings to health-check tests.
ENG-39 Implemented Taurus Metric Collectors deployment test resource_accessibility_test.py.
ENG-39 Implemented Taurus Engine deployment/resource_accessibility_test.py
ENG-39 Integrate deployment tests into Taurus pipeline scripts.
I tested the initilize/refresh/update taurus pipeline scripts from my dev laptop against my test ec2 instances. I tested without the `-t destructive-tests` option, as that triggers the failing `results_quality_test.py`.

ENG-39 Implement safe acceptance tests to execute in the taurus production/staging refresh pipelines

---

infrastructure/saltcellar/dotfiles/files/bash_profile_skeleton.sh
infrastructure/saltcellar/dotfiles/files/bashrc_skeleton.sh

Move the PATH assignment to bashrc_skeleton so it works for non-interactive sessions too

---

taurus/pipeline/scripts/overrides/taurus/conf/supervisord.conf

Fixup the supervisord.conf file used in taurus deployment script(s)

---

taurus.metric_collectors/taurus/metric_collectors/collectorsdb/__init__.py

This is a follow-on PR on the tails of "tweet collector stall" PR #341
ENG-67 Don't nest the collectorsdb._EngineSingleton's thread lock inside the process lock in getEngine().
ENG-67 Lock both process lock and thread lock in _EngineSingleton.reset() and note that it's "For use by tests only!".
CC @scottpurdy @oxtopus

ENG-67 Clean up locking logic in collectorsdb._EngineSingleton

---

taurus.metric_collectors/tests/integration/collectorsdb_test.py

ENG-69 Fixed race condition in collectorsdb integration test TestTransientErrorHandling.testTransientErrorRetryDecorator

---

unicorn/backend/unicorn_backend/model_runner.py

ENG-70 Return log-scaled anomaly likelihood

---

infrastructure/infrastructure/utilities/nupic/build_commands.py

Account for .py suffix added to test command

---

unicorn/backend/unicorn_backend/stats_schema.json

ENG-73 Updated comment in unicorn_backend/stats_schema.json

---

unicorn/tests/js/unit/ModelServer_test.js

ENG-70: Fix Model Server test using log-scaled anomaly likelihood

---

unicorn/frontend/lib/ModelServer.js

UNI-149: Calculate max concurrency based on memory and cpu

---

unicorn/README.md
unicorn/frontend/browser/actions/FileUpload.js
unicorn/frontend/browser/actions/ListFiles.js
unicorn/frontend/browser/actions/ListMetrics.js
unicorn/frontend/browser/actions/StartModel.js
unicorn/frontend/browser/app.js
unicorn/frontend/browser/components/Main.jsx
unicorn/frontend/lib/DatabaseServer.js
unicorn/frontend/lib/ModelServer.js
unicorn/frontend/lib/UserError.js
unicorn/frontend/main.js
unicorn/gulpfile.babel.js
unicorn/package.json
unicorn/tests/js/unit/FileServer_test.js
unicorn/tests/js/unit/FileStore_test.js

UNI-187 #comment code review fixes
Please see each commit msg.
@lscheinkman @marionleborgne

UNI-187 #comment code review fixes

---

unicorn/frontend/browser/components/Chart.jsx

Unicorn GUI: Init component prop properly :)

---

infrastructure/infrastructure/utilities/htm_it_server.py

'pylint' fixes.

---

infrastructure/saltcellar/nta-nucleus/settings.sls

We stopped installing upstream git, so ensure we have our git in the PATH
@jcasner @shantanoo, please CR

Make sure that /usr/local/git/bin is in PATH for cronjobs

---

unicorn/package.json

Sync node.js versions in salt and in Unicorn codebase.

Sync node.js versions in salt and in Unicorn codebase.

---

nta.utils/nta/utils/error_handling.py

Fixes https://jira.numenta.com/browse/ENG-78

Fixes ENG-78

---

nta.utils/nta/utils/error_handling.py
nta.utils/tests/integration/synchronous_amqp_client_test.py

Actual change in https://github.com/numenta/numenta-apps/commit/14155caf6fa008360e8ee917a7d6c183b6cf208f to exclude whitespace changes

ENG-55 remove  _hasEvent()

---

nta.utils/nta/utils/supervisor_utils.py
nta.utils/nta/utils/tools/supervisord_state.py
nta.utils/setup.py
taurus.monitoring/taurus/monitoring/supervisord_monitor/supervisord_monitor.py
taurus/pipeline/scripts/update-remote-taurus-servers.sh

Merge and deploy this before #396!

Eng 76 install console script but dont use it yet

---

nta.utils/nta/utils/error_handling.py
nta.utils/tests/unit/error_handling_test.py

Would like feedback on on proposed unit tests.
https://jira.numenta.com/browse/ENG-50
@scottpurdy?

Proposed unit tests for the retry decorator.

---

nta.utils/nta/utils/tools/supervisord_state.py

ENG-76 Fixup type-related bugs discovered in review

---

nta.utils/nta/utils/tools/supervisord_state.py

re: https://github.com/numenta/numenta-apps/pull/407/files#r41830053
@vitaly-krugl you should lobby to include your comments in the coding style guide, especially since pylint doesn't complain.  It's likely to turn up again since you're arguing personal preference, and having a concrete policy will help to not waste anyone's time.

ENG-76 Remove defaults from function signature per @vitaly-krugl

---

unicorn/frontend/browser/actions/ModelError.js
unicorn/frontend/browser/actions/StartModel.js
unicorn/frontend/browser/lib/ModelClientIPC.js
unicorn/frontend/lib/ModelServer.js
unicorn/frontend/lib/ModelServerIPC.js
unicorn/tests/js/integration/README.md
unicorn/tests/js/unit/ModelServer_test.js

Better model error handling and fix unicorn model test

---

htm.it/htm/it/app/aws/asg_utils.py
htm.it/htm/it/app/aws/cloudwatch_utils.py
htm.it/htm/it/app/aws/ec2_utils.py
htm.it/htm/it/app/aws/elb_utils.py
htm.it/htm/it/app/aws/opsworks_utils.py
htm.it/htm/it/app/aws/s3_utils.py
htm.it/htm/it/test_utils/app/test_case_base.py
htm.it/tests/py/integration/app/autostacks_test.py
htm.it/tests/py/integration/app/runtime/metric_collector_int_test.py
htmengine/tests/integration/result_quality_test.py

Fixes https://jira.numenta.com/browse/ENG-51

ENG-51 Use nta.utils retry decorator in numeta-apps

---

htm.it/htm/it/app/aws/asg_utils.py
htm.it/htm/it/app/aws/cloudwatch_utils.py
htm.it/htm/it/app/aws/ec2_utils.py
htm.it/htm/it/app/aws/elb_utils.py
htm.it/htm/it/app/aws/opsworks_utils.py
htm.it/htm/it/app/aws/s3_utils.py
htm.it/htm/it/test_utils/app/test_case_base.py
htm.it/tests/py/integration/app/autostacks_test.py
htm.it/tests/py/integration/app/runtime/metric_collector_int_test.py
htmengine/tests/integration/result_quality_test.py

Reverts numenta/numenta-apps#412 due to https://github.com/numenta/numenta-apps/pull/412#issuecomment-148514083

Revert "ENG-51 Use nta.utils retry decorator in numeta-apps"

---

infrastructure/saltcellar/numenta-python/init.sls

Updates the anaconda python installer (aka gs-anaconda) to 2.7.10.
@jcasner / @shantanoo please CR

TAUR-1301 Update Anaconda python to 2.7.10

---

unicorn/README.md
unicorn/backend/README.md

@oxtopus updated README instructions.
cc @brev @lscheinkman

updated readme instructions for the backend of unicorn

---

unicorn/tests/js/mocha.opts
unicorn/tests/js/mocha.pipeline.opts
unicorn/tests/js/unit/ModelServer_test.js

in reply to https://github.com/numenta/numenta-apps/commit/3de55db5a584b77a41abdf5d07b17fbcb7e1dd67#commitcomment-13865526
@brev Let me know if this works for you

Add configurable timeout options to mocha tests 

---

pipeline_controller

@vitaly-krugl this will fix the issue you noticed

Update pipeline_controller to work with the new pipeline names

---

unicorn/backend/setup.py

@oxtopus @scottpurdy @rhyolight 
Fixing the error that happened with #454 when running `python setup.py test`

fix test location calculation

---

unicorn/frontend/browser/app.js
unicorn/frontend/browser/components/Chart.jsx
unicorn/frontend/browser/components/FileDetails.jsx
unicorn/frontend/browser/components/Main.jsx
unicorn/frontend/browser/index.html
unicorn/package.json

@brev Need to update to new version of material-ui which requires new version of react and other dependencies.

Update to 'fluxible:1.0.1', 'react:0.14.2' and 'material-ui:0.13.1

---

unicorn/frontend/browser/components/FileDetails.jsx
unicorn/frontend/browser/lib/Constants.js
unicorn/frontend/lib/FileServer.js
unicorn/package.json

@marionleborgne 
As we discussed, this PR does not display the list but it will guess and store the timestamp format to the database so it could be used by the model runner
CC: @brev

UNI-225: Guess timestamp format based on the data and store in the database #send-for-review

---

taurus/README.md
taurus/taurus/engine/set_api_key.py
taurus/tests/unit/set_api_key_test.py

ENG-95 Addressed Austin's code review feedback from PR #459.
ENG-95 Also added information about taurus-set-api-key in Taurus README.md.

ENG-95 Addressed Austin's code review feedback from PR #459.

---

imbu/.eslintrc
imbu/.pylintrc
imbu/Dockerfile
imbu/README.md
imbu/conf/nginx-fluent.conf
imbu/conf/supervisord.conf
imbu/engine/fluent_api.py
imbu/engine/imbu_tp.json
imbu/gui/browser/actions/search-clear.js
imbu/gui/browser/actions/search-query.js
imbu/gui/browser/app.js
imbu/gui/browser/components/main.jsx
imbu/gui/browser/components/search-history.jsx
imbu/gui/browser/components/search-results.jsx
imbu/gui/browser/components/search.jsx
imbu/gui/browser/stores/search.js
imbu/gui/loader.js
imbu/gui/main.js
imbu/gulpfile.babel.js
imbu/package.json
imbu/requirements.txt
imbu/start_imbu.sh
infrastructure/coreos/config.rb

IMBU-10: Update IMBU and create docker image

---

imbu/engine/fluent_api.py

IMBU-10: Remove debug message

---

infrastructure/infrastructure/utilities/nupic/build_commands.py

@oxtopus please review
Merging b/c I don't see any way to test the Jenkins pipeline without merging.

Make sure pycapnp is installed.

---

unicorn/frontend/browser/actions/CreateModel.js
unicorn/frontend/browser/actions/DeleteFile.js
unicorn/frontend/browser/actions/FileDetailsSave.js
unicorn/frontend/browser/actions/HideModel.js
unicorn/frontend/browser/actions/ShowMetricDetails.js
unicorn/frontend/browser/actions/ShowModel.js
unicorn/frontend/browser/components/FileList.jsx
unicorn/frontend/browser/components/ModelList.jsx
unicorn/frontend/browser/lib/Constants.js
unicorn/frontend/browser/stores/FileStore.js
unicorn/frontend/browser/stores/ModelStore.js
unicorn/package.json

UNI-236: Metric Menu / UNI-241: Create Model

---

unicorn/js/browser/actions/ExportModelResults.js
unicorn/js/browser/components/FileList.jsx
unicorn/js/main/DatabaseService.js
unicorn/package.json
unicorn/tests/js/unit/DatabaseService_test.js

UNI-243: Export model results #send-for-review

---

taurus-mobile/ios/Taurus/Base.lproj/Main.storyboard
taurus-mobile/ios/src/controllers/InstanceViewController.swift
taurus-mobile/ios/src/controllers/TutorialController.swift
taurus-mobile/ios/src/controllers/TwitterViewController.swift

Taurus mobile ios (1.0.104)

---

taurus.monitoring/taurus/monitoring/latency_monitor/model_latency_monitor.py
taurus.monitoring/tests/unit/model_latency_monitor_test.py

DEVOPS-70 apply market hour logic to all metrics, not just stock

---

imbu/conf/supervisord.conf
imbu/engine/fluent_api.py

Run IMBU in concurrency=1, with no `--idle` option.

IMBU-14 Pare down uwsgi options in supervisor config, minor cleanup

---

unicorn/js/browser/actions/FileUpload.js
unicorn/js/browser/actions/ListFiles.js
unicorn/js/browser/actions/ListMetrics.js
unicorn/js/browser/actions/StartModel.js
unicorn/js/browser/components/FileDetails.jsx
unicorn/js/browser/components/FileList.jsx
unicorn/js/database/schema/File.json
unicorn/js/database/schema/Metric.json
unicorn/js/database/schema/MetricData.json
unicorn/js/main/DatabaseService.js
unicorn/js/main/FileService.js
unicorn/js/main/ModelService.js
unicorn/js/main/Utils.js
unicorn/tests/js/unit/DatabaseService_test.js

@brev Please review.
This PR covers database part of deleting Metrics and it's dependent data.
The connection to the UI will be in a separate PR.

UNI-242: Optimize database key schema representing file, metric and data hierarchies #send-for-review

---

unicorn/js/browser/actions/DeleteFile.js
unicorn/js/browser/stores/FileStore.js

@brev Connecting  #496 to the `DeleteFile` action

UNI-238: Delete metrics and data when deleting file

---

imbu/engine/fluent_api.py
imbu/engine/imbu_tp.json

Run CioWindows model as Imbu default

---

imbu/.eslintignore
imbu/.eslintrc
imbu/.pylintrc
imbu/Dockerfile
imbu/conf/supervisord.conf
imbu/engine/fluent_api.py
imbu/gui/browser/app.js
imbu/gui/browser/components/main.jsx
imbu/gui/browser/components/search-history.jsx
imbu/gui/browser/components/search-results.jsx
imbu/gui/browser/components/search.jsx
imbu/gui/browser/index.html
imbu/package.json
imbu/setup.py
imbu/start_imbu.sh

IMBU-21: Update UI packages and fix table copy and paste

---

imbu/engine/fluent_api.py
imbu/gui/browser/app.js
imbu/gui/browser/components/search-results.jsx

IMBU-41: Show all samples on startup

---

imbu/engine/fluent_api.py
imbu/gui/browser/actions/search-query.js
imbu/gui/browser/app.js
imbu/gui/browser/components/search-history.jsx
imbu/gui/browser/components/search-results.jsx
imbu/gui/browser/components/search.jsx
imbu/gui/browser/stores/search.js

CC: @BoltzmannBrain 
It depends on #506. Relevant commit e54f4ad

IMBU-36: Add model selection

---

imbu/Dockerfile

Remove VOLUME from Dockerfile which was interfering with subsequent COPY commands.

IMBU-54 remove VOLUME

---

taurus/pipeline/scripts/refresh-remote-taurus-servers.sh

CC @oxtopus, @scottpurdy 
This fixes regression that I introduced in https://github.com/numenta/numenta-apps/pull/515

ENG-98 Add missing double-quote; plus minor comment improvement.

---

taurus/pipeline/scripts/refresh-remote-taurus-servers.sh

ENG-98 Fix regression: use sudo when calling rabbitmqctl.

---

taurus/pipeline/scripts/refresh-remote-taurus-servers.sh

ENG-98 Fix regression in import of ModelCheckpointMgr.

---

unicorn/js/browser/actions/LoadMetricData.js
unicorn/js/browser/components/FileDetails.jsx
unicorn/js/browser/components/FileList.jsx
unicorn/js/browser/components/Model.jsx

@marionleborgne This should fix the missing raw data chart

UNI-289: Load raw data from file system if not available from database

---

infrastructure/infrastructure/utilities/nupic/build_commands.py

Attempting fix of internal pipeline.

Update nupic.core build steps.

---

taurus-mobile/ios/Settings.bundle/Root.plist
taurus-mobile/ios/Taurus.xcodeproj/project.pbxproj
taurus-mobile/ios/Taurus/Base.lproj/LaunchScreen.storyboard
taurus-mobile/ios/Taurus/Base.lproj/Main.storyboard
taurus-mobile/ios/Taurus/CustomMenuController.swift
taurus-mobile/ios/src/app/AppDelegate.swift
taurus-mobile/ios/src/controllers/InstanceDetailsViewController.swift
taurus-mobile/ios/src/controllers/TwitterViewController.swift
taurus-mobile/ios/src/service/NotificationService.swift

Fixes TAUR-1742, TAUR-1750, TAUR-1730, TAUR-1752

---

nta.utils/nta/utils/tools/supervisord_state.py

ENG-84 Fix regression by suppressing xmlrpclib.Fault while waiting for supervisord to stop

---

unicorn/js/browser/actions/FileDetailsSave.js
unicorn/js/browser/components/FileDetails.jsx

UNI-283 Fix auto-create models on new data upload
https://jira.numenta.com/browse/UNI-283
@lscheinkman @marionleborgne please review at some point in future.
cc @cbaranski

UNI-283 Fix auto-create models on new data upload

---

imbu/engine/fluent_api.py

As it turns out, the problem seemed to be the placement of `model.numLabels = 0`
This appears to be working now.

Re-enable load/save

---

taurus.metric_collectors/tests/unit/delete_companies_test.py
taurus/setup.py

CC @oxtopus 
ENG-98 Address Austin's code review feedback regarding sys.executable.
Also fix up a mock spec in delete_companies_test.py.

ENG-98 Address Austin's code review feedback regarding sys.executable.

---

imbu/README.md

Add details of usage w/ docker

---

imbu/engine/fluent_api.py

Requires https://github.com/numenta/nupic.research/pull/394

IMBU-53 Use external cache directory for CioEncoder cache

---

imbu/engine/fluent_api.py
imbu/gui/browser/components/search.jsx

* Models are trained by feeding them one token at a time.
* Also removed the CioWindows model for now; it'll likely be replaced with a model that uses NuPIC's Network API.
@oxtopus please review.

Imbu runs NLP models with new token-level scheme

---

imbu/.babelrc
imbu/gui/browser/actions/search-query.js
imbu/gui/browser/app.js
imbu/gui/browser/components/main.jsx
imbu/gui/browser/components/search-history.jsx
imbu/gui/browser/components/search-results.jsx
imbu/gui/browser/components/search.jsx
imbu/gui/browser/stores/search.js
imbu/gulpfile.babel.js
imbu/package.json

IMBU-56: Show results side by side

---

imbu/engine/fluent_api.py

To use a common results-formatting method between the Imbu app and the nupic.research script.

Imbu method to format results

---

imbu/engine/fluent_api.py

Relies on [nupic.research #414](https://github.com/numenta/nupic.research/pull/414)

Accomodate for changes to formatResults() in Imbu runner

---

unicorn/scripts/Windows64/README.md
unicorn/scripts/Windows64/build_portable_python_with_nupic.ps1

Relates to UNI-302
cc @lscheinkman @scottpurdy

build script to create a portable python distribution /w nupic on W8 x64

---

imbu/gui/browser/components/search-results.jsx

IMBU-82: Make room for column header

---

imbu/Dockerfile

Add 'python-matplotlib' to image

---

imbu/requirements.txt

Upgrade nupic version

---

imbu/engine/fluent_api.py

https://github.com/numenta/nupic.research/pull/445

Update Imbu formatResults method

---

imbu/engine/fluent_api.py
imbu/gui/browser/components/search-results.jsx
imbu/gui/browser/components/search.jsx
imbu/gui/browser/stores/search.js

IMBU-25: Highlight words and show score as tooltip

---

imbu/README.md
imbu/destructive-build-and-refresh-container.sh
imbu/graceful-build-and-refresh-container.sh

IMBU-94: Add `IMBU_DOCKER_OPTIONS` environment variable

---

unicorn/package.json

See https://github.com/babel/babel-eslint/issues/243

Temporary fix for eslint's dependency.

---

unicorn/py/unicorn_backend/input_opt_schema.json
unicorn/py/unicorn_backend/model_runner_2.py
unicorn/py/unicorn_backend/tests/integration/model_runner_2_test.py

Please review
CC @marionleborgne @lscheinkman

UNI-307 Support passing CSV file path in model_runner_2.

---

unicorn/scripts/OSX/README.md
unicorn/scripts/OSX/build-python.sh

I tested the script on a fresh VM (OSX Yosemite) so that should be good to go with Bamboo. Also, I created a backup of the clean VM. Let me know if you need it for Bamboo. It has XCode and cmake installed - that's all that is needed to run the script (as explained in `README.md`)
This should wrap up https://jira.numenta.com/browse/UNI-302
@lscheinkman @scottpurdy @oxtopus please review.
Thanks!

Osx python build

---

docker-build-all.sh

Remove obsolete docker-build-all.sh file

---

unicorn/js/browser/lib/Unicorn/ModelClient.js
unicorn/js/main/ModelServiceIPC.js

Figured out how to use new API for Electron `ipc` after upgrade.

Figured out how to use new API for Electron `ipc` after upgrade.

---

unicorn/py/requirements.txt
unicorn/scripts/OSX/build-python.sh
unicorn/scripts/Windows64/README.md
unicorn/scripts/Windows64/build_portable_python_with_nupic.ps1
unicorn/scripts/Windows64/simple_build_portable_python_with_nupic.ps1

Updated windows build script

---

unicorn/js/browser/components/FileDetails.jsx
unicorn/js/browser/components/FileList.jsx
unicorn/js/browser/components/Logo.jsx
unicorn/js/browser/components/Model.jsx

UNI-306 A. Remove extraneous button "secondary" property (fixes mis-coloring)

UNI-306 A. Remove extraneous button "secondary" property

---

unicorn/js/browser/components/Logo.jsx

UNI-306 #comment C. Fix React/MUI component children warning in console.
Moved title outside of Logo Avatar.
https://jira.numenta.com/browse/UNI-306

UNI-306 C. Fix React/MUI component children warning in console.

---

unicorn/py/unicorn_backend/param_finder.py
unicorn/py/unicorn_backend/param_finder_runner.py
unicorn/tests/py/unit/unicorn_backend/param_finder_runner_test.py
unicorn/tests/py/unit/unicorn_backend/param_finder_test.py

@marionleborgne @vitaly-krugl 
Address the rest of Vitaly's comment for https://github.com/numenta/numenta-apps/pull/571
Summary
* Use Doxygen convention for documentation in param_finder
* Add end-to-end test for param_finder runner
* Add tests for find_parameters, _getModelParams
* Fix many code styling issues

[UNI-299] Implementation of paramFinder and paramFinder runner 

---

imbu/gui/browser/stores/search.js

IMBU-118: Sort results by maxScore then by sumScore

---

imbu/gui/browser/components/search-results.jsx

IMBU-109: Remove maxScore highlight

---

unicorn/js/browser/actions/FileUpload.js
unicorn/js/browser/actions/StartModel.js
unicorn/js/browser/lib/Constants.js
unicorn/js/browser/lib/Unicorn/DatabaseClient.js
unicorn/js/database/schema/File.json
unicorn/js/database/schema/Metric.json
unicorn/js/database/schema/MetricData.json
unicorn/js/main/DatabaseService.js
unicorn/js/main/ModelService2.js
unicorn/js/schemas/index.js
unicorn/py/unicorn_backend/agg_opt_schema.json
unicorn/py/unicorn_backend/input_opt_schema.json
unicorn/py/unicorn_backend/input_opt_schema_param_finder.json
unicorn/py/unicorn_backend/model_opt_schema.json
unicorn/py/unicorn_backend/model_runner_2.py
unicorn/py/unicorn_backend/param_finder_output_schema.json
unicorn/py/unicorn_backend/stats_schema.json
unicorn/tests/js/unit/DatabaseService_test.js

@marionleborgne Here is #628 moved to this branch

UNI-311: Store param_finder results in database

---

unicorn/js/browser/components/FileList.jsx
unicorn/js/browser/components/Logo.jsx
unicorn/js/browser/components/Model.jsx
unicorn/js/browser/lib/MaterialUI/UnicornTheme.js
unicorn/js/config/default.json

UNI-314 B. Implement new metric status indicators, left of metric label instead of right. Re-color and set with Theme. Add model button colors. etc.
@lscheinkman @marionleborgne please review sometime.

UNI-314 B. Implement new metric status indicators, left of metric label

---

unicorn/js/browser/components/Main.jsx
unicorn/js/browser/components/Model.jsx
unicorn/js/config/default.json
unicorn/js/main/FileService.js
unicorn/package.json

UNI-314 #comment D. Switch our File Upload dialog from Browser to System/Electron. With the system dialog, we have much more control, and now:
- File upload starts in users Desktop dir
- File upload restricted to CSV files only
- etc.
FYI @lscheinkman @marionleborgne please review at your convenience thanks

UNI-314 #comment D. Switch our File Upload dialog from Browser to

---

unicorn/js/browser/index.html
unicorn/js/main/MainMenu.js
unicorn/js/main/index.js
unicorn/package.json

UNI-314 E. Init the top-level system Menu (File/Open..., etc). Not tied to any actions yet, but it's ready to be extended.  And, clean up html template. Tiny bit of refactoring.
FYI @lscheinkman @marionleborgne

UNI-314 E. Init the top-level system Menu (File/Open..., etc). Not active yet.

---

unicorn/js/browser/components/FileList.jsx
unicorn/js/browser/components/Logo.jsx
unicorn/js/browser/components/ModelList.jsx
unicorn/js/browser/index.html
unicorn/js/browser/lib/MaterialUI/UnicornTheme.js
unicorn/js/config/default.json

UNI-306 #comment H. Default background messaging when no models visible. Other styling.
@lscheinkman @marionleborgne FYI

UNI-306 H. Default background messaging when no models visible

---

unicorn/README.md
unicorn/py/unicorn_backend/model_runner_2.py

UNI-306 #comment Fix failing unit test in master, and update docs (make python path issue more prominent and global.)

UNI-306 Fix failing unit test in master, and update docs about python path

---

unicorn/js/browser/actions/FileDetailsSave.js
unicorn/js/browser/actions/FileUpload.js
unicorn/js/browser/actions/ListMetrics.js
unicorn/js/browser/actions/StartApplication.js
unicorn/js/browser/app.js
unicorn/js/browser/components/FileDetails.jsx
unicorn/js/browser/components/FileList.jsx
unicorn/js/browser/lib/Unicorn/DatabaseClient.js
unicorn/js/browser/lib/Unicorn/FileClient.js
unicorn/js/browser/stores/FileStore.js
unicorn/js/browser/stores/MetricDataStore.js
unicorn/js/browser/stores/MetricStore.js
unicorn/js/main/FileService.js
unicorn/tests/js/unit/FileStore_test.js

UNI-320: Create MetricStore, Refactor 'ListMetrics' and 'FileUpload' actions

---

unicorn/js/browser/components/CreateModelDialog.jsx
unicorn/js/browser/components/Main.jsx
unicorn/js/browser/components/Model.jsx
unicorn/js/browser/stores/MetricStore.js

It works! @lscheinkman @brev  (except that the charts have a little issue and don't change amplitude with the anomaly likelihood values)

All the pieces are connected

---

unicorn/js/browser/actions/FileUpload.js

Fix FileUpload in OOBE branch
@marionleborgne @lscheinkman

UNI-306 #comment Fix File Upload in OOBE branch

---

unicorn/js/browser/components/Chart.jsx
unicorn/js/browser/components/ModelData.jsx
unicorn/js/browser/stores/ModelDataStore.js

UNI-306 #comment OOBE fix bring back Anomaly Bars
cc @marionleborgne @lscheinkman

UNI-306 #comment OOBE fix bring back Anomaly Bars

---

unicorn/js/browser/actions/ReceiveParamFinderData.js
unicorn/js/browser/actions/ShowCreateModelDialog.js
unicorn/js/browser/actions/StartModel.js
unicorn/js/browser/actions/StartParamFinder.js
unicorn/js/browser/components/CreateModelDialog.jsx
unicorn/js/browser/components/FileDetails.jsx
unicorn/js/browser/components/Main.jsx
unicorn/js/browser/components/Model.jsx
unicorn/js/browser/lib/Unicorn/ModelClient.js
unicorn/js/main/ParamFinderService.js

UNI-306 #comment OOBE Fix Lint Warnings
cc @marionleborgne @lscheinkman

UNI-306 #comment OOBE Fix Lint Warnings

---

htmengine/README.md
nta.utils/nta/utils/logging_support_raw.py

Fixes #655
CC @rhyolight, @cbaranski

Clarify configuration of `APPLICATION_CONFIG_PATH` in htmengine/README.md

---

unicorn/README.md
unicorn/js/browser/components/Chart.jsx
unicorn/js/browser/components/ModelData.jsx
unicorn/js/browser/lib/Dygraphs/RangeSelectorBarChartPlugin.js
unicorn/package.json

UNI-306 #comment J. 
- Lock range selector width, always 100 points now.
- Remove js-csp
- Fix a small off-by-one pixel bug in range selector anomaly bars, thanks for review @marionleborgne.
https://jira.numenta.com/browse/UNI-306
ready for review @marionleborgne @lscheinkman

UNI-306 #comment J. Lock range selector width, always 100 points now.

---

unicorn/README.md

Added instruction to the Develop section for installing without the python bundle.

---

unicorn/tests/js/unit/services/FileService_test.js

@vitaly-krugl This PR should fix the test failure you found in https://github.com/numenta/numenta-apps/pull/667#issuecomment-189420250
Let me know if it works for you.

Fix FileService test

---

unicorn/js/browser/actions/FileUpload.js
unicorn/js/browser/components/CreateModelDialog.jsx
unicorn/js/browser/components/ModelData.jsx
unicorn/js/browser/lib/Dygraphs/RangeSelectorBarChartPlugin.js
unicorn/js/main/ModelService.js
unicorn/js/main/Utils.js

Fix a few more lints, it's now all clean.
@lscheinkman @marionleborgne @vitaly-krugl

2016 02 26 few more lint fixes

---

unicorn/js/browser/actions/StartModel.js
unicorn/js/browser/components/Chart.jsx
unicorn/js/browser/components/CreateModelDialog.jsx
unicorn/js/config/default.json
unicorn/js/main/ModelService.js

UNI-306 #comment FLOW A: Send correct Raw vs. Aggregate params to Model Runner from Model Creation dialog. This will allow for later access to display Raw or Agg data.
Please review @lscheinkman @marionleborgne

Uni 306 flow a raw vs agg send correct params

---

unicorn/scripts/OSX/build-python.sh

disable pip cache usage

---

unicorn/js/browser/components/ModelData.jsx
unicorn/js/browser/stores/ModelDataStore.js

@brev @marionleborgne This should limit some of the UI updates when showing multiple charts

Only updates ModelData component if the model data has changed

---

unicorn/.babelrc
unicorn/js/browser/actions/ShowFileDetails.js
unicorn/js/browser/components/FileDetails.jsx
unicorn/js/browser/stores/FileDetailsStore.js
unicorn/js/main/DatabaseService.js
unicorn/js/main/FileService.js
unicorn/package.json
unicorn/tests/js/fixtures/ignored-fields.csv
unicorn/tests/js/integration/services/DatabaseService_test.js
unicorn/tests/js/integration/services/FileService_test.js
unicorn/tests/js/unit/stores/FileDetailsStore_test.js

@marionleborgne Please review, should fix open **FileUpload** and **Validation** issues
Addresses UNI-345, UNI-347, UNI-338

UNI-345: Address FileUpload feedback

---

unicorn/js/browser/components/FileDetails.jsx

@marionleborgne It should address https://github.com/numenta/numenta-apps/pull/683#issuecomment-195695244

UNI-345: Show file size in KB instead of bytes

---

unicorn/js/browser/actions/AddShowModel.js
unicorn/js/browser/components/FileDetails.jsx
unicorn/js/browser/components/FileList.jsx
unicorn/js/browser/components/ModelData.jsx

UNI-328 #comment Clean-up fixes.
- Left nav metric checkbox only takes 1 click now.
- etc. (see each commit msg).
FYI @lscheinkman @marionleborgne 
BTW, I'm still working on one more PR separately, to remember position on chart between "show non-agg data" checkbox toggles.

UNI-328 Clean up fixes

---

taurus/README.md

Update README.md: tie creation of the .dynamodb directory to the use of the DynamoDB emulation tool.

---

unicorn/js/browser/actions/AddShowModel.js
unicorn/tests/js/unit/actions/AddShowModel_test.js

Add unit test for new AddShowModel Fluxible action.
Please review @lscheinkman @marionleborgne

Add unit test for new AddShowModel Fluxible action.

---

unicorn/js/browser/app.js
unicorn/js/browser/components/Chart.jsx
unicorn/js/browser/lib/HTMStudio/ModelClient.js

@brev Please review and let me know if it works with your new PR.
CC: @marionleborgne

UNI-373: buffer modal data changes updating every 100ms

---

unicorn/js/browser/components/FileList.jsx
unicorn/js/browser/components/Main.jsx
unicorn/js/config/default.json

UNI-350 #comment Reorganize Left Menu layout.
https://jira.numenta.com/browse/UNI-350
@marionleborgne or @lscheinkman please review thanks.

UNI-350 #comment Reorganize Left Menu layout.

---

unicorn/js/browser/components/FileList.jsx
unicorn/js/browser/components/Logo.jsx
unicorn/js/browser/components/Main.jsx
unicorn/js/browser/components/Model.jsx

UNI-306 UNI-314 #comment General visual styling and pixel pushing to match mockups.
https://jira.numenta.com/browse/UNI-306
https://jira.numenta.com/browse/UNI-314
cc @lscheinkman @marionleborgne @cbaranski

UNI-306 UNI-314 General visual styling and pixel pushing to match mockups.

---

unicorn/js/browser/components/Chart.jsx
unicorn/js/browser/components/ModelData.jsx

UNI-306 #comment Lock chart Y Axis value height.
https://jira.numenta.com/browse/UNI-306
Please review @marionleborgne.  cc @lscheinkman

UNI-306 Lock chart Y Axis value height.

---

unicorn/js/browser/components/CreateModelDialog.jsx
unicorn/js/browser/components/Model.jsx
unicorn/js/config/default.json

UNI-375: Add results summary button

---

unicorn/js/browser/components/CreateModelDialog.jsx

@marionleborgne 
This PR will bypass second dialog if param_finder does not find any valid aggregation and start the model with the `raw` data by default.
You can test with small files.

UNI-377: Bypass aggregation dialog if param_finder does not find any valid aggregation

---

unicorn/js/browser/components/FileList.jsx

@marionleborgne I think this is the last dialog with the wrong button.

UNI-378: Make delete file dialog buttons consistent with other dialogs

---

unicorn/js/browser/assets/styles/index.css
unicorn/js/browser/components/FileList.jsx
unicorn/js/config/default.json

@marionleborgne , @brev 
Add both spinner (UNI-351) and tooltip (UNI-359) to model status indicator

UNI-351: Update model status icon and tooltip

---

unicorn/js/browser/components/FileList.jsx

UNI-349: Click on file collapse metrics

---

unicorn/js/browser/components/FileList.jsx

@marionleborgne It should also fix UNI-381

UNI-284: Stop and hide models when deleting files

---

unicorn/app/browser/components/Model.jsx
unicorn/app/browser/components/ModelProgress.jsx
unicorn/app/browser/lib/HTMStudio/ModelClient.js
unicorn/app/browser/stores/MetricDataStore.js
unicorn/app/browser/stores/ModelDataStore.js
unicorn/app/config/default.json
unicorn/app/package.json
unicorn/package.json
unicorn/tests/js/mocha.pipeline.opts
unicorn/webpack.config.babel.js

UNI-384: Add progress and rearrange buttons

---

unicorn/app/browser/components/Model.jsx

@marionleborgne sub task of UNI-385

UNI-417: Move "Show Aggregation" checkbox to the top

---

unicorn/app/browser/components/Model.jsx

@marionleborgne Fix problem when the model fails to complete when not using aggregations.
Test using 'home_data.csv' sample file

Fix models with no aggregation

---

unicorn/app/browser/components/Model.jsx
unicorn/app/browser/components/ModelData.jsx
unicorn/app/browser/lib/Constants.js
unicorn/app/browser/lib/browser-utils.js
unicorn/app/common/Constants.js
unicorn/app/common/common-utils.js
unicorn/app/main/DatabaseService.js

@marionleborgne This PR updates the anomaly text to 'HIGH/MEDIUM/LOW' (UNI-389) and all other related issues:
- UNI-388: CSV Export
- UNI-418: Chart Legend Style
Please review

UNI-389: Update anomaly text and all related issues

---

taurus.metric_collectors/taurus/metric_collectors/xignite/check_company_symbols.py

TAUR-1895 Added diagnostic logging to capture xignite error messages from failed self-check.

---

unicorn/app/browser/components/Chart.jsx
unicorn/app/browser/components/Model.jsx

Last part of PR #754. Show the HTM settings in the results summary dialog. Text might be updated during next marketing meeting, but the functionality is there.

UNI-428: HTM settings in summary

---

unicorn/app/browser/components/Chart.jsx

UNI-432: Unlock scroll while the model is active

---

unicorn/app/browser/components/FileDetails.jsx
unicorn/app/browser/components/Model.jsx
unicorn/app/config/default.json

Incorporate marketing feedback to update dialog text and other related cosmetic changes

Incorporate marketing feedback 

---

unicorn/app/browser/components/Model.jsx
unicorn/app/browser/components/ModelData.jsx

Replaces #776 
/cc @marionleborgne

Gap detection: handle case where aggregation window is wide

---

unicorn/app/browser/components/CreateModelDialog.jsx
unicorn/app/browser/stores/CreateModelStore.js

- Fix bug that causes model to run without aggInfo
- Fix bug where the CreateModelDialog state is not reset when re-opening the dialog

Fix Advanced Settings Bugs

---

unicorn/app/browser/components/Model.jsx

Fix results summary

---

unicorn/app/browser/actions/StartModel.js
unicorn/app/browser/components/Chart.jsx
unicorn/app/browser/components/ModelData.jsx
unicorn/app/browser/lib/Constants.js
unicorn/app/browser/lib/Dygraphs/AnomalyBarChartUnderlay.js
unicorn/app/browser/lib/Dygraphs/CustomDygraph.js
unicorn/app/browser/lib/Dygraphs/RangeSelectorBarChartPlugin.js
unicorn/app/browser/stores/MetricStore.js

Branches merged in master (at https://github.com/numenta/numenta-apps/commit/b6d63d19d3af7648329ecdc22a3aecf5b2ca85b9)
* https://github.com/numenta/numenta-apps/pull/793
* https://github.com/numenta/numenta-apps/pull/792
* https://github.com/numenta/numenta-apps/pull/789
* https://github.com/numenta/numenta-apps/pull/788
We need two more fixes to make this branch stable for the beta:
1. @mrcslws: Fix zoom reset when "show non-aggregated data" checkbox is selected / unselected
2. @marionleborgne: Disable point-and-click when model is running [1]
[1] since there is currently no fix for the bug: "left/right panning is broken when the model is running"

Second stable release for private beta (with custom zoom)

---

unicorn/app/browser/actions/StartModel.js
unicorn/app/browser/components/Chart.jsx
unicorn/app/browser/components/ModelData.jsx
unicorn/app/browser/lib/Constants.js
unicorn/app/browser/lib/Dygraphs/AnomalyBarChartUnderlay.js
unicorn/app/browser/lib/Dygraphs/CustomDygraph.js
unicorn/app/browser/lib/Dygraphs/RangeSelectorBarChartPlugin.js
unicorn/app/browser/stores/MetricStore.js

See details here: https://github.com/numenta/numenta-apps/pull/795

HTM studio private beta w custom zoom

---

unicorn/app/browser/components/Chart.jsx
unicorn/app/browser/components/ModelList.jsx

UNI-433 Make charts stop disappearing

---

unicorn/.gitignore
unicorn/app/package.json
unicorn/package.json
unicorn/scripts/download_python.js

UNI-502: Use local 'portable_python' if available downloading only when necessary

---

unicorn/package.json
unicorn/tests/js/unit/actions/AddShowModel_test.js
unicorn/tests/js/unit/actions/DeleteFile_test.js
unicorn/tests/js/unit/actions/MockGATracker.js

Build is green again.
See https://ci.numenta.com/browse/UN-UN8-24/
CC: @marionleborgne

Fix Unicorn build

---

unicorn/app/browser/entry.js
unicorn/app/main/AutoUpdate.js
unicorn/app/main/index.js

@marionleborgne I could not reproduce but added a check just in case there is a race condition.
Also removed auto updater dialog messages such as "Update check failed: (null)" that may occur on network or other errors.

UNI-485: Make sure application is initialized before starting

---

unicorn/app/browser/components/Model.jsx

UNI-467: Set min width to model data chart

---

unicorn/app/browser/actions/CloseModel.js
unicorn/app/browser/actions/CloseParamFinder.js
unicorn/app/browser/lib/Constants.js
unicorn/app/browser/lib/HTMStudio/ModelClient.js
unicorn/app/browser/lib/HTMStudio/ParamFinderClient.js
unicorn/app/browser/stores/ModelStore.js

@marionleborgne @andrewmalta13 Please review

UNI-528: Don't call stop action after process closes. Use close action instead

---

unicorn/app/main/MainMenu.js

@lscheinkman @oxtopus could you test on windows?

UNI-520 bring back menus on windows.

---

unicorn/app/browser/components/CreateModelDialog.jsx
unicorn/app/browser/stores/CreateModelStore.js
unicorn/app/config/default.json
unicorn/app/main/UserError.js

@marionleborgne Please review
CC: @cbaranski

UNI-528: Disable model creation on param finder failures

---

unicorn/app/main/MainMenu.js

UNI-532 bigger about menu box

---

unicorn/app/package.json

Version 0.0.6

---

unicorn/py/unicorn_backend/utils/na.py

addresses a comment from @vitaly-krugl.
Same logic, just more pythonic.

UNI-496/503/511 changes a line to be more pythonic

---

unicorn/app/browser/components/CreateModelDialog.jsx

@marionleborgne Should guard against race condition found in windows VM.

UNI-556: Wait for param finder results

---

unicorn/app/main/AutoUpdate.js

@marionleborgne Auto updates should also work on windows, I will update the `README` on a separate PR
@cbaranski FYI, this was causing the exception on installation

UNI-541: Fix Windows Auto updates

---

unicorn/app/package.json

Version 0.0.8

---

unicorn/README.md
unicorn/app/main/ModelService.js
unicorn/app/main/ParamFinderService.js

Thanks @mrcslws and @lscheinkman

UNI-575 ignore env variables like PYTHONPATH

---

unicorn/app/browser/components/Model.jsx

UNI-565 updated text and redirecting to the FAQ with info about the license

---

unicorn/app/config/default.json

New text updated to:
cc @lscheinkman @cbaranski

UNI-562 updated delete file confirmation message

---

unicorn/app/package.json

Version 0.0.9

---

unicorn/app/package.json

cc @cbaranski @lscheinkman 
And thanks @mrcslws for unblocking us with the potential showstopper.

Version 0.0.10

---

unicorn/scripts/OSX/build-python.sh

Fix relative path when script is called by "source" or "." operator

---

unicorn/py/unicorn_backend/param_finder.py

This is fixing Len's bug. @ywcui1990 please have a look. The sample file is attached in UNI-581
cc @lscheinkman

UNI-581: handle case where the sampling rate is slower than 4 weeks

---

unicorn/py/unicorn_backend/param_finder.py

@lscheinkman This should fix the Unicorn build. 
@ywcui1990 please review, since this is touching the param finder.

UNI-586: fix broken build

---

unicorn/scripts/Windows64/build_portable_python_with_nupic.ps1
unicorn/scripts/Windows64/simple_build_portable_python_with_nupic.ps1

Use our get-pip.py url

---

htmengine/htmengine/model_swapper/model_runner.py
htmengine/htmengine/model_swapper/slot_agent.py
htmengine/htmengine/model_swapper/swap_controller.py
htmengine/htmengine/model_swapper/utils.py

Fixes #893
Someone's earlier PR failed to fix them all up, so this should do the trick.

logExceptions now takes a logger not a logger-getter function

---

htmengine/requirements.txt
install-taurus-metric-collectors.sh
install-taurus-monitoring.sh
install-taurus.sh
taurus_engine/Dockerfile
taurus_engine/requirements.txt
taurus_metric_collectors/Dockerfile
taurus_metric_collectors/requirements.txt

TAUR-2059 Break from depending on numenta/nupic:latest docker image

---

ci/bamboo/cleanup-taurus-ephemera.sh
ci/bamboo/deploy-taurus.sh
ci/bamboo/test-taurus.sh

The inline scripts from bamboo have been translated into scripts that are tracked here.

TAUR-2058 Move inline bamboo tasks into git

---

ci/bamboo/deploy-taurus.sh

to account for some tests that can only run while services are stopped.

TAUR-2058 Invoke deployment tests separately

---

burnrate-metric/.gitignore
burnrate-metric/Dockerfile
burnrate-metric/LICENSE.txt
burnrate-metric/README.md
burnrate-metric/Rakefile
burnrate-metric/burnrate-metric
burnrate-metric/burnrate_collect_data.py
burnrate-metric/calculate_burn_rate.py
burnrate-metric/price_table_builder.py

Used `git subtree` to keep the history
FYI: @cbaranski

DEVOPS-368: Move burnrate-metric to numenta-apps
